//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Activation) DeepCopyInto(out *Activation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Activation.
func (in *Activation) DeepCopy() *Activation {
	if in == nil {
		return nil
	}
	out := new(Activation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Activation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivationInitParameters) DeepCopyInto(out *ActivationInitParameters) {
	*out = *in
	if in.ActivationID != nil {
		in, out := &in.ActivationID, &out.ActivationID
		*out = new(string)
		**out = **in
	}
	if in.AutoAcknowledgeRuleWarnings != nil {
		in, out := &in.AutoAcknowledgeRuleWarnings, &out.AutoAcknowledgeRuleWarnings
		*out = new(bool)
		**out = **in
	}
	if in.ComplianceRecord != nil {
		in, out := &in.ComplianceRecord, &out.ComplianceRecord
		*out = make([]ComplianceRecordInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Contact != nil {
		in, out := &in.Contact, &out.Contact
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(string)
		**out = **in
	}
	if in.Note != nil {
		in, out := &in.Note, &out.Note
		*out = new(string)
		**out = **in
	}
	if in.PropertyID != nil {
		in, out := &in.PropertyID, &out.PropertyID
		*out = new(string)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivationInitParameters.
func (in *ActivationInitParameters) DeepCopy() *ActivationInitParameters {
	if in == nil {
		return nil
	}
	out := new(ActivationInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivationList) DeepCopyInto(out *ActivationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Activation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivationList.
func (in *ActivationList) DeepCopy() *ActivationList {
	if in == nil {
		return nil
	}
	out := new(ActivationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ActivationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivationObservation) DeepCopyInto(out *ActivationObservation) {
	*out = *in
	if in.ActivationID != nil {
		in, out := &in.ActivationID, &out.ActivationID
		*out = new(string)
		**out = **in
	}
	if in.AutoAcknowledgeRuleWarnings != nil {
		in, out := &in.AutoAcknowledgeRuleWarnings, &out.AutoAcknowledgeRuleWarnings
		*out = new(bool)
		**out = **in
	}
	if in.ComplianceRecord != nil {
		in, out := &in.ComplianceRecord, &out.ComplianceRecord
		*out = make([]ComplianceRecordObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Contact != nil {
		in, out := &in.Contact, &out.Contact
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(string)
		**out = **in
	}
	if in.Note != nil {
		in, out := &in.Note, &out.Note
		*out = new(string)
		**out = **in
	}
	if in.PropertyID != nil {
		in, out := &in.PropertyID, &out.PropertyID
		*out = new(string)
		**out = **in
	}
	if in.RuleErrors != nil {
		in, out := &in.RuleErrors, &out.RuleErrors
		*out = make([]ActivationRuleErrorsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(float64)
		**out = **in
	}
	if in.Warnings != nil {
		in, out := &in.Warnings, &out.Warnings
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivationObservation.
func (in *ActivationObservation) DeepCopy() *ActivationObservation {
	if in == nil {
		return nil
	}
	out := new(ActivationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivationParameters) DeepCopyInto(out *ActivationParameters) {
	*out = *in
	if in.ActivationID != nil {
		in, out := &in.ActivationID, &out.ActivationID
		*out = new(string)
		**out = **in
	}
	if in.AutoAcknowledgeRuleWarnings != nil {
		in, out := &in.AutoAcknowledgeRuleWarnings, &out.AutoAcknowledgeRuleWarnings
		*out = new(bool)
		**out = **in
	}
	if in.ComplianceRecord != nil {
		in, out := &in.ComplianceRecord, &out.ComplianceRecord
		*out = make([]ComplianceRecordParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Contact != nil {
		in, out := &in.Contact, &out.Contact
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(string)
		**out = **in
	}
	if in.Note != nil {
		in, out := &in.Note, &out.Note
		*out = new(string)
		**out = **in
	}
	if in.PropertyID != nil {
		in, out := &in.PropertyID, &out.PropertyID
		*out = new(string)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivationParameters.
func (in *ActivationParameters) DeepCopy() *ActivationParameters {
	if in == nil {
		return nil
	}
	out := new(ActivationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivationRuleErrorsInitParameters) DeepCopyInto(out *ActivationRuleErrorsInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivationRuleErrorsInitParameters.
func (in *ActivationRuleErrorsInitParameters) DeepCopy() *ActivationRuleErrorsInitParameters {
	if in == nil {
		return nil
	}
	out := new(ActivationRuleErrorsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivationRuleErrorsObservation) DeepCopyInto(out *ActivationRuleErrorsObservation) {
	*out = *in
	if in.BehaviorName != nil {
		in, out := &in.BehaviorName, &out.BehaviorName
		*out = new(string)
		**out = **in
	}
	if in.Detail != nil {
		in, out := &in.Detail, &out.Detail
		*out = new(string)
		**out = **in
	}
	if in.ErrorLocation != nil {
		in, out := &in.ErrorLocation, &out.ErrorLocation
		*out = new(string)
		**out = **in
	}
	if in.Instance != nil {
		in, out := &in.Instance, &out.Instance
		*out = new(string)
		**out = **in
	}
	if in.StatusCode != nil {
		in, out := &in.StatusCode, &out.StatusCode
		*out = new(float64)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivationRuleErrorsObservation.
func (in *ActivationRuleErrorsObservation) DeepCopy() *ActivationRuleErrorsObservation {
	if in == nil {
		return nil
	}
	out := new(ActivationRuleErrorsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivationRuleErrorsParameters) DeepCopyInto(out *ActivationRuleErrorsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivationRuleErrorsParameters.
func (in *ActivationRuleErrorsParameters) DeepCopy() *ActivationRuleErrorsParameters {
	if in == nil {
		return nil
	}
	out := new(ActivationRuleErrorsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivationSpec) DeepCopyInto(out *ActivationSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivationSpec.
func (in *ActivationSpec) DeepCopy() *ActivationSpec {
	if in == nil {
		return nil
	}
	out := new(ActivationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivationStatus) DeepCopyInto(out *ActivationStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivationStatus.
func (in *ActivationStatus) DeepCopy() *ActivationStatus {
	if in == nil {
		return nil
	}
	out := new(ActivationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Bootstrap) DeepCopyInto(out *Bootstrap) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Bootstrap.
func (in *Bootstrap) DeepCopy() *Bootstrap {
	if in == nil {
		return nil
	}
	out := new(Bootstrap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Bootstrap) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapInitParameters) DeepCopyInto(out *BootstrapInitParameters) {
	*out = *in
	if in.ContractID != nil {
		in, out := &in.ContractID, &out.ContractID
		*out = new(string)
		**out = **in
	}
	if in.GroupID != nil {
		in, out := &in.GroupID, &out.GroupID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ProductID != nil {
		in, out := &in.ProductID, &out.ProductID
		*out = new(string)
		**out = **in
	}
	if in.UseHostnameBucket != nil {
		in, out := &in.UseHostnameBucket, &out.UseHostnameBucket
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapInitParameters.
func (in *BootstrapInitParameters) DeepCopy() *BootstrapInitParameters {
	if in == nil {
		return nil
	}
	out := new(BootstrapInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapList) DeepCopyInto(out *BootstrapList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Bootstrap, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapList.
func (in *BootstrapList) DeepCopy() *BootstrapList {
	if in == nil {
		return nil
	}
	out := new(BootstrapList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BootstrapList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapObservation) DeepCopyInto(out *BootstrapObservation) {
	*out = *in
	if in.AssetID != nil {
		in, out := &in.AssetID, &out.AssetID
		*out = new(string)
		**out = **in
	}
	if in.ContractID != nil {
		in, out := &in.ContractID, &out.ContractID
		*out = new(string)
		**out = **in
	}
	if in.GroupID != nil {
		in, out := &in.GroupID, &out.GroupID
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ProductID != nil {
		in, out := &in.ProductID, &out.ProductID
		*out = new(string)
		**out = **in
	}
	if in.UseHostnameBucket != nil {
		in, out := &in.UseHostnameBucket, &out.UseHostnameBucket
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapObservation.
func (in *BootstrapObservation) DeepCopy() *BootstrapObservation {
	if in == nil {
		return nil
	}
	out := new(BootstrapObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapParameters) DeepCopyInto(out *BootstrapParameters) {
	*out = *in
	if in.ContractID != nil {
		in, out := &in.ContractID, &out.ContractID
		*out = new(string)
		**out = **in
	}
	if in.GroupID != nil {
		in, out := &in.GroupID, &out.GroupID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ProductID != nil {
		in, out := &in.ProductID, &out.ProductID
		*out = new(string)
		**out = **in
	}
	if in.UseHostnameBucket != nil {
		in, out := &in.UseHostnameBucket, &out.UseHostnameBucket
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapParameters.
func (in *BootstrapParameters) DeepCopy() *BootstrapParameters {
	if in == nil {
		return nil
	}
	out := new(BootstrapParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapSpec) DeepCopyInto(out *BootstrapSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapSpec.
func (in *BootstrapSpec) DeepCopy() *BootstrapSpec {
	if in == nil {
		return nil
	}
	out := new(BootstrapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapStatus) DeepCopyInto(out *BootstrapStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapStatus.
func (in *BootstrapStatus) DeepCopy() *BootstrapStatus {
	if in == nil {
		return nil
	}
	out := new(BootstrapStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertStatusInitParameters) DeepCopyInto(out *CertStatusInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertStatusInitParameters.
func (in *CertStatusInitParameters) DeepCopy() *CertStatusInitParameters {
	if in == nil {
		return nil
	}
	out := new(CertStatusInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertStatusObservation) DeepCopyInto(out *CertStatusObservation) {
	*out = *in
	if in.Hostname != nil {
		in, out := &in.Hostname, &out.Hostname
		*out = new(string)
		**out = **in
	}
	if in.ProductionStatus != nil {
		in, out := &in.ProductionStatus, &out.ProductionStatus
		*out = new(string)
		**out = **in
	}
	if in.StagingStatus != nil {
		in, out := &in.StagingStatus, &out.StagingStatus
		*out = new(string)
		**out = **in
	}
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertStatusObservation.
func (in *CertStatusObservation) DeepCopy() *CertStatusObservation {
	if in == nil {
		return nil
	}
	out := new(CertStatusObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertStatusParameters) DeepCopyInto(out *CertStatusParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertStatusParameters.
func (in *CertStatusParameters) DeepCopy() *CertStatusParameters {
	if in == nil {
		return nil
	}
	out := new(CertStatusParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceRecordInitParameters) DeepCopyInto(out *ComplianceRecordInitParameters) {
	*out = *in
	if in.NoncomplianceReasonEmergency != nil {
		in, out := &in.NoncomplianceReasonEmergency, &out.NoncomplianceReasonEmergency
		*out = make([]NoncomplianceReasonEmergencyInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NoncomplianceReasonNoProductionTraffic != nil {
		in, out := &in.NoncomplianceReasonNoProductionTraffic, &out.NoncomplianceReasonNoProductionTraffic
		*out = make([]NoncomplianceReasonNoProductionTrafficInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NoncomplianceReasonNone != nil {
		in, out := &in.NoncomplianceReasonNone, &out.NoncomplianceReasonNone
		*out = make([]NoncomplianceReasonNoneInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NoncomplianceReasonOther != nil {
		in, out := &in.NoncomplianceReasonOther, &out.NoncomplianceReasonOther
		*out = make([]NoncomplianceReasonOtherInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceRecordInitParameters.
func (in *ComplianceRecordInitParameters) DeepCopy() *ComplianceRecordInitParameters {
	if in == nil {
		return nil
	}
	out := new(ComplianceRecordInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceRecordNoncomplianceReasonEmergencyInitParameters) DeepCopyInto(out *ComplianceRecordNoncomplianceReasonEmergencyInitParameters) {
	*out = *in
	if in.TicketID != nil {
		in, out := &in.TicketID, &out.TicketID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceRecordNoncomplianceReasonEmergencyInitParameters.
func (in *ComplianceRecordNoncomplianceReasonEmergencyInitParameters) DeepCopy() *ComplianceRecordNoncomplianceReasonEmergencyInitParameters {
	if in == nil {
		return nil
	}
	out := new(ComplianceRecordNoncomplianceReasonEmergencyInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceRecordNoncomplianceReasonEmergencyObservation) DeepCopyInto(out *ComplianceRecordNoncomplianceReasonEmergencyObservation) {
	*out = *in
	if in.TicketID != nil {
		in, out := &in.TicketID, &out.TicketID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceRecordNoncomplianceReasonEmergencyObservation.
func (in *ComplianceRecordNoncomplianceReasonEmergencyObservation) DeepCopy() *ComplianceRecordNoncomplianceReasonEmergencyObservation {
	if in == nil {
		return nil
	}
	out := new(ComplianceRecordNoncomplianceReasonEmergencyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceRecordNoncomplianceReasonEmergencyParameters) DeepCopyInto(out *ComplianceRecordNoncomplianceReasonEmergencyParameters) {
	*out = *in
	if in.TicketID != nil {
		in, out := &in.TicketID, &out.TicketID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceRecordNoncomplianceReasonEmergencyParameters.
func (in *ComplianceRecordNoncomplianceReasonEmergencyParameters) DeepCopy() *ComplianceRecordNoncomplianceReasonEmergencyParameters {
	if in == nil {
		return nil
	}
	out := new(ComplianceRecordNoncomplianceReasonEmergencyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceRecordNoncomplianceReasonNoProductionTrafficInitParameters) DeepCopyInto(out *ComplianceRecordNoncomplianceReasonNoProductionTrafficInitParameters) {
	*out = *in
	if in.TicketID != nil {
		in, out := &in.TicketID, &out.TicketID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceRecordNoncomplianceReasonNoProductionTrafficInitParameters.
func (in *ComplianceRecordNoncomplianceReasonNoProductionTrafficInitParameters) DeepCopy() *ComplianceRecordNoncomplianceReasonNoProductionTrafficInitParameters {
	if in == nil {
		return nil
	}
	out := new(ComplianceRecordNoncomplianceReasonNoProductionTrafficInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceRecordNoncomplianceReasonNoProductionTrafficObservation) DeepCopyInto(out *ComplianceRecordNoncomplianceReasonNoProductionTrafficObservation) {
	*out = *in
	if in.TicketID != nil {
		in, out := &in.TicketID, &out.TicketID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceRecordNoncomplianceReasonNoProductionTrafficObservation.
func (in *ComplianceRecordNoncomplianceReasonNoProductionTrafficObservation) DeepCopy() *ComplianceRecordNoncomplianceReasonNoProductionTrafficObservation {
	if in == nil {
		return nil
	}
	out := new(ComplianceRecordNoncomplianceReasonNoProductionTrafficObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceRecordNoncomplianceReasonNoProductionTrafficParameters) DeepCopyInto(out *ComplianceRecordNoncomplianceReasonNoProductionTrafficParameters) {
	*out = *in
	if in.TicketID != nil {
		in, out := &in.TicketID, &out.TicketID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceRecordNoncomplianceReasonNoProductionTrafficParameters.
func (in *ComplianceRecordNoncomplianceReasonNoProductionTrafficParameters) DeepCopy() *ComplianceRecordNoncomplianceReasonNoProductionTrafficParameters {
	if in == nil {
		return nil
	}
	out := new(ComplianceRecordNoncomplianceReasonNoProductionTrafficParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceRecordNoncomplianceReasonNoneInitParameters) DeepCopyInto(out *ComplianceRecordNoncomplianceReasonNoneInitParameters) {
	*out = *in
	if in.CustomerEmail != nil {
		in, out := &in.CustomerEmail, &out.CustomerEmail
		*out = new(string)
		**out = **in
	}
	if in.PeerReviewedBy != nil {
		in, out := &in.PeerReviewedBy, &out.PeerReviewedBy
		*out = new(string)
		**out = **in
	}
	if in.TicketID != nil {
		in, out := &in.TicketID, &out.TicketID
		*out = new(string)
		**out = **in
	}
	if in.UnitTested != nil {
		in, out := &in.UnitTested, &out.UnitTested
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceRecordNoncomplianceReasonNoneInitParameters.
func (in *ComplianceRecordNoncomplianceReasonNoneInitParameters) DeepCopy() *ComplianceRecordNoncomplianceReasonNoneInitParameters {
	if in == nil {
		return nil
	}
	out := new(ComplianceRecordNoncomplianceReasonNoneInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceRecordNoncomplianceReasonNoneObservation) DeepCopyInto(out *ComplianceRecordNoncomplianceReasonNoneObservation) {
	*out = *in
	if in.CustomerEmail != nil {
		in, out := &in.CustomerEmail, &out.CustomerEmail
		*out = new(string)
		**out = **in
	}
	if in.PeerReviewedBy != nil {
		in, out := &in.PeerReviewedBy, &out.PeerReviewedBy
		*out = new(string)
		**out = **in
	}
	if in.TicketID != nil {
		in, out := &in.TicketID, &out.TicketID
		*out = new(string)
		**out = **in
	}
	if in.UnitTested != nil {
		in, out := &in.UnitTested, &out.UnitTested
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceRecordNoncomplianceReasonNoneObservation.
func (in *ComplianceRecordNoncomplianceReasonNoneObservation) DeepCopy() *ComplianceRecordNoncomplianceReasonNoneObservation {
	if in == nil {
		return nil
	}
	out := new(ComplianceRecordNoncomplianceReasonNoneObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceRecordNoncomplianceReasonNoneParameters) DeepCopyInto(out *ComplianceRecordNoncomplianceReasonNoneParameters) {
	*out = *in
	if in.CustomerEmail != nil {
		in, out := &in.CustomerEmail, &out.CustomerEmail
		*out = new(string)
		**out = **in
	}
	if in.PeerReviewedBy != nil {
		in, out := &in.PeerReviewedBy, &out.PeerReviewedBy
		*out = new(string)
		**out = **in
	}
	if in.TicketID != nil {
		in, out := &in.TicketID, &out.TicketID
		*out = new(string)
		**out = **in
	}
	if in.UnitTested != nil {
		in, out := &in.UnitTested, &out.UnitTested
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceRecordNoncomplianceReasonNoneParameters.
func (in *ComplianceRecordNoncomplianceReasonNoneParameters) DeepCopy() *ComplianceRecordNoncomplianceReasonNoneParameters {
	if in == nil {
		return nil
	}
	out := new(ComplianceRecordNoncomplianceReasonNoneParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceRecordNoncomplianceReasonOtherInitParameters) DeepCopyInto(out *ComplianceRecordNoncomplianceReasonOtherInitParameters) {
	*out = *in
	if in.OtherNoncomplianceReason != nil {
		in, out := &in.OtherNoncomplianceReason, &out.OtherNoncomplianceReason
		*out = new(string)
		**out = **in
	}
	if in.TicketID != nil {
		in, out := &in.TicketID, &out.TicketID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceRecordNoncomplianceReasonOtherInitParameters.
func (in *ComplianceRecordNoncomplianceReasonOtherInitParameters) DeepCopy() *ComplianceRecordNoncomplianceReasonOtherInitParameters {
	if in == nil {
		return nil
	}
	out := new(ComplianceRecordNoncomplianceReasonOtherInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceRecordNoncomplianceReasonOtherObservation) DeepCopyInto(out *ComplianceRecordNoncomplianceReasonOtherObservation) {
	*out = *in
	if in.OtherNoncomplianceReason != nil {
		in, out := &in.OtherNoncomplianceReason, &out.OtherNoncomplianceReason
		*out = new(string)
		**out = **in
	}
	if in.TicketID != nil {
		in, out := &in.TicketID, &out.TicketID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceRecordNoncomplianceReasonOtherObservation.
func (in *ComplianceRecordNoncomplianceReasonOtherObservation) DeepCopy() *ComplianceRecordNoncomplianceReasonOtherObservation {
	if in == nil {
		return nil
	}
	out := new(ComplianceRecordNoncomplianceReasonOtherObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceRecordNoncomplianceReasonOtherParameters) DeepCopyInto(out *ComplianceRecordNoncomplianceReasonOtherParameters) {
	*out = *in
	if in.OtherNoncomplianceReason != nil {
		in, out := &in.OtherNoncomplianceReason, &out.OtherNoncomplianceReason
		*out = new(string)
		**out = **in
	}
	if in.TicketID != nil {
		in, out := &in.TicketID, &out.TicketID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceRecordNoncomplianceReasonOtherParameters.
func (in *ComplianceRecordNoncomplianceReasonOtherParameters) DeepCopy() *ComplianceRecordNoncomplianceReasonOtherParameters {
	if in == nil {
		return nil
	}
	out := new(ComplianceRecordNoncomplianceReasonOtherParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceRecordObservation) DeepCopyInto(out *ComplianceRecordObservation) {
	*out = *in
	if in.NoncomplianceReasonEmergency != nil {
		in, out := &in.NoncomplianceReasonEmergency, &out.NoncomplianceReasonEmergency
		*out = make([]NoncomplianceReasonEmergencyObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NoncomplianceReasonNoProductionTraffic != nil {
		in, out := &in.NoncomplianceReasonNoProductionTraffic, &out.NoncomplianceReasonNoProductionTraffic
		*out = make([]NoncomplianceReasonNoProductionTrafficObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NoncomplianceReasonNone != nil {
		in, out := &in.NoncomplianceReasonNone, &out.NoncomplianceReasonNone
		*out = make([]NoncomplianceReasonNoneObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NoncomplianceReasonOther != nil {
		in, out := &in.NoncomplianceReasonOther, &out.NoncomplianceReasonOther
		*out = make([]NoncomplianceReasonOtherObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceRecordObservation.
func (in *ComplianceRecordObservation) DeepCopy() *ComplianceRecordObservation {
	if in == nil {
		return nil
	}
	out := new(ComplianceRecordObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceRecordParameters) DeepCopyInto(out *ComplianceRecordParameters) {
	*out = *in
	if in.NoncomplianceReasonEmergency != nil {
		in, out := &in.NoncomplianceReasonEmergency, &out.NoncomplianceReasonEmergency
		*out = make([]NoncomplianceReasonEmergencyParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NoncomplianceReasonNoProductionTraffic != nil {
		in, out := &in.NoncomplianceReasonNoProductionTraffic, &out.NoncomplianceReasonNoProductionTraffic
		*out = make([]NoncomplianceReasonNoProductionTrafficParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NoncomplianceReasonNone != nil {
		in, out := &in.NoncomplianceReasonNone, &out.NoncomplianceReasonNone
		*out = make([]NoncomplianceReasonNoneParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NoncomplianceReasonOther != nil {
		in, out := &in.NoncomplianceReasonOther, &out.NoncomplianceReasonOther
		*out = make([]NoncomplianceReasonOtherParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceRecordParameters.
func (in *ComplianceRecordParameters) DeepCopy() *ComplianceRecordParameters {
	if in == nil {
		return nil
	}
	out := new(ComplianceRecordParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostnamesInitParameters) DeepCopyInto(out *HostnamesInitParameters) {
	*out = *in
	if in.CertProvisioningType != nil {
		in, out := &in.CertProvisioningType, &out.CertProvisioningType
		*out = new(string)
		**out = **in
	}
	if in.CertStatus != nil {
		in, out := &in.CertStatus, &out.CertStatus
		*out = make([]CertStatusInitParameters, len(*in))
		copy(*out, *in)
	}
	if in.CnameFrom != nil {
		in, out := &in.CnameFrom, &out.CnameFrom
		*out = new(string)
		**out = **in
	}
	if in.CnameTo != nil {
		in, out := &in.CnameTo, &out.CnameTo
		*out = new(string)
		**out = **in
	}
	if in.CnameType != nil {
		in, out := &in.CnameType, &out.CnameType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostnamesInitParameters.
func (in *HostnamesInitParameters) DeepCopy() *HostnamesInitParameters {
	if in == nil {
		return nil
	}
	out := new(HostnamesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostnamesObservation) DeepCopyInto(out *HostnamesObservation) {
	*out = *in
	if in.CertProvisioningType != nil {
		in, out := &in.CertProvisioningType, &out.CertProvisioningType
		*out = new(string)
		**out = **in
	}
	if in.CertStatus != nil {
		in, out := &in.CertStatus, &out.CertStatus
		*out = make([]CertStatusObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CnameFrom != nil {
		in, out := &in.CnameFrom, &out.CnameFrom
		*out = new(string)
		**out = **in
	}
	if in.CnameTo != nil {
		in, out := &in.CnameTo, &out.CnameTo
		*out = new(string)
		**out = **in
	}
	if in.CnameType != nil {
		in, out := &in.CnameType, &out.CnameType
		*out = new(string)
		**out = **in
	}
	if in.EdgeHostnameID != nil {
		in, out := &in.EdgeHostnameID, &out.EdgeHostnameID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostnamesObservation.
func (in *HostnamesObservation) DeepCopy() *HostnamesObservation {
	if in == nil {
		return nil
	}
	out := new(HostnamesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostnamesParameters) DeepCopyInto(out *HostnamesParameters) {
	*out = *in
	if in.CertProvisioningType != nil {
		in, out := &in.CertProvisioningType, &out.CertProvisioningType
		*out = new(string)
		**out = **in
	}
	if in.CertStatus != nil {
		in, out := &in.CertStatus, &out.CertStatus
		*out = make([]CertStatusParameters, len(*in))
		copy(*out, *in)
	}
	if in.CnameFrom != nil {
		in, out := &in.CnameFrom, &out.CnameFrom
		*out = new(string)
		**out = **in
	}
	if in.CnameTo != nil {
		in, out := &in.CnameTo, &out.CnameTo
		*out = new(string)
		**out = **in
	}
	if in.CnameType != nil {
		in, out := &in.CnameType, &out.CnameType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostnamesParameters.
func (in *HostnamesParameters) DeepCopy() *HostnamesParameters {
	if in == nil {
		return nil
	}
	out := new(HostnamesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Include) DeepCopyInto(out *Include) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Include.
func (in *Include) DeepCopy() *Include {
	if in == nil {
		return nil
	}
	out := new(Include)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Include) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncludeActivation) DeepCopyInto(out *IncludeActivation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncludeActivation.
func (in *IncludeActivation) DeepCopy() *IncludeActivation {
	if in == nil {
		return nil
	}
	out := new(IncludeActivation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IncludeActivation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncludeActivationComplianceRecordInitParameters) DeepCopyInto(out *IncludeActivationComplianceRecordInitParameters) {
	*out = *in
	if in.NoncomplianceReasonEmergency != nil {
		in, out := &in.NoncomplianceReasonEmergency, &out.NoncomplianceReasonEmergency
		*out = make([]ComplianceRecordNoncomplianceReasonEmergencyInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NoncomplianceReasonNoProductionTraffic != nil {
		in, out := &in.NoncomplianceReasonNoProductionTraffic, &out.NoncomplianceReasonNoProductionTraffic
		*out = make([]ComplianceRecordNoncomplianceReasonNoProductionTrafficInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NoncomplianceReasonNone != nil {
		in, out := &in.NoncomplianceReasonNone, &out.NoncomplianceReasonNone
		*out = make([]ComplianceRecordNoncomplianceReasonNoneInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NoncomplianceReasonOther != nil {
		in, out := &in.NoncomplianceReasonOther, &out.NoncomplianceReasonOther
		*out = make([]ComplianceRecordNoncomplianceReasonOtherInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncludeActivationComplianceRecordInitParameters.
func (in *IncludeActivationComplianceRecordInitParameters) DeepCopy() *IncludeActivationComplianceRecordInitParameters {
	if in == nil {
		return nil
	}
	out := new(IncludeActivationComplianceRecordInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncludeActivationComplianceRecordObservation) DeepCopyInto(out *IncludeActivationComplianceRecordObservation) {
	*out = *in
	if in.NoncomplianceReasonEmergency != nil {
		in, out := &in.NoncomplianceReasonEmergency, &out.NoncomplianceReasonEmergency
		*out = make([]ComplianceRecordNoncomplianceReasonEmergencyObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NoncomplianceReasonNoProductionTraffic != nil {
		in, out := &in.NoncomplianceReasonNoProductionTraffic, &out.NoncomplianceReasonNoProductionTraffic
		*out = make([]ComplianceRecordNoncomplianceReasonNoProductionTrafficObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NoncomplianceReasonNone != nil {
		in, out := &in.NoncomplianceReasonNone, &out.NoncomplianceReasonNone
		*out = make([]ComplianceRecordNoncomplianceReasonNoneObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NoncomplianceReasonOther != nil {
		in, out := &in.NoncomplianceReasonOther, &out.NoncomplianceReasonOther
		*out = make([]ComplianceRecordNoncomplianceReasonOtherObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncludeActivationComplianceRecordObservation.
func (in *IncludeActivationComplianceRecordObservation) DeepCopy() *IncludeActivationComplianceRecordObservation {
	if in == nil {
		return nil
	}
	out := new(IncludeActivationComplianceRecordObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncludeActivationComplianceRecordParameters) DeepCopyInto(out *IncludeActivationComplianceRecordParameters) {
	*out = *in
	if in.NoncomplianceReasonEmergency != nil {
		in, out := &in.NoncomplianceReasonEmergency, &out.NoncomplianceReasonEmergency
		*out = make([]ComplianceRecordNoncomplianceReasonEmergencyParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NoncomplianceReasonNoProductionTraffic != nil {
		in, out := &in.NoncomplianceReasonNoProductionTraffic, &out.NoncomplianceReasonNoProductionTraffic
		*out = make([]ComplianceRecordNoncomplianceReasonNoProductionTrafficParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NoncomplianceReasonNone != nil {
		in, out := &in.NoncomplianceReasonNone, &out.NoncomplianceReasonNone
		*out = make([]ComplianceRecordNoncomplianceReasonNoneParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NoncomplianceReasonOther != nil {
		in, out := &in.NoncomplianceReasonOther, &out.NoncomplianceReasonOther
		*out = make([]ComplianceRecordNoncomplianceReasonOtherParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncludeActivationComplianceRecordParameters.
func (in *IncludeActivationComplianceRecordParameters) DeepCopy() *IncludeActivationComplianceRecordParameters {
	if in == nil {
		return nil
	}
	out := new(IncludeActivationComplianceRecordParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncludeActivationInitParameters) DeepCopyInto(out *IncludeActivationInitParameters) {
	*out = *in
	if in.AutoAcknowledgeRuleWarnings != nil {
		in, out := &in.AutoAcknowledgeRuleWarnings, &out.AutoAcknowledgeRuleWarnings
		*out = new(bool)
		**out = **in
	}
	if in.ComplianceRecord != nil {
		in, out := &in.ComplianceRecord, &out.ComplianceRecord
		*out = make([]IncludeActivationComplianceRecordInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ContractID != nil {
		in, out := &in.ContractID, &out.ContractID
		*out = new(string)
		**out = **in
	}
	if in.GroupID != nil {
		in, out := &in.GroupID, &out.GroupID
		*out = new(string)
		**out = **in
	}
	if in.IncludeID != nil {
		in, out := &in.IncludeID, &out.IncludeID
		*out = new(string)
		**out = **in
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(string)
		**out = **in
	}
	if in.Note != nil {
		in, out := &in.Note, &out.Note
		*out = new(string)
		**out = **in
	}
	if in.NotifyEmails != nil {
		in, out := &in.NotifyEmails, &out.NotifyEmails
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncludeActivationInitParameters.
func (in *IncludeActivationInitParameters) DeepCopy() *IncludeActivationInitParameters {
	if in == nil {
		return nil
	}
	out := new(IncludeActivationInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncludeActivationList) DeepCopyInto(out *IncludeActivationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IncludeActivation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncludeActivationList.
func (in *IncludeActivationList) DeepCopy() *IncludeActivationList {
	if in == nil {
		return nil
	}
	out := new(IncludeActivationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IncludeActivationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncludeActivationObservation) DeepCopyInto(out *IncludeActivationObservation) {
	*out = *in
	if in.AutoAcknowledgeRuleWarnings != nil {
		in, out := &in.AutoAcknowledgeRuleWarnings, &out.AutoAcknowledgeRuleWarnings
		*out = new(bool)
		**out = **in
	}
	if in.ComplianceRecord != nil {
		in, out := &in.ComplianceRecord, &out.ComplianceRecord
		*out = make([]IncludeActivationComplianceRecordObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ContractID != nil {
		in, out := &in.ContractID, &out.ContractID
		*out = new(string)
		**out = **in
	}
	if in.GroupID != nil {
		in, out := &in.GroupID, &out.GroupID
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IncludeID != nil {
		in, out := &in.IncludeID, &out.IncludeID
		*out = new(string)
		**out = **in
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(string)
		**out = **in
	}
	if in.Note != nil {
		in, out := &in.Note, &out.Note
		*out = new(string)
		**out = **in
	}
	if in.NotifyEmails != nil {
		in, out := &in.NotifyEmails, &out.NotifyEmails
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Validations != nil {
		in, out := &in.Validations, &out.Validations
		*out = new(string)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncludeActivationObservation.
func (in *IncludeActivationObservation) DeepCopy() *IncludeActivationObservation {
	if in == nil {
		return nil
	}
	out := new(IncludeActivationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncludeActivationParameters) DeepCopyInto(out *IncludeActivationParameters) {
	*out = *in
	if in.AutoAcknowledgeRuleWarnings != nil {
		in, out := &in.AutoAcknowledgeRuleWarnings, &out.AutoAcknowledgeRuleWarnings
		*out = new(bool)
		**out = **in
	}
	if in.ComplianceRecord != nil {
		in, out := &in.ComplianceRecord, &out.ComplianceRecord
		*out = make([]IncludeActivationComplianceRecordParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ContractID != nil {
		in, out := &in.ContractID, &out.ContractID
		*out = new(string)
		**out = **in
	}
	if in.GroupID != nil {
		in, out := &in.GroupID, &out.GroupID
		*out = new(string)
		**out = **in
	}
	if in.IncludeID != nil {
		in, out := &in.IncludeID, &out.IncludeID
		*out = new(string)
		**out = **in
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(string)
		**out = **in
	}
	if in.Note != nil {
		in, out := &in.Note, &out.Note
		*out = new(string)
		**out = **in
	}
	if in.NotifyEmails != nil {
		in, out := &in.NotifyEmails, &out.NotifyEmails
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncludeActivationParameters.
func (in *IncludeActivationParameters) DeepCopy() *IncludeActivationParameters {
	if in == nil {
		return nil
	}
	out := new(IncludeActivationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncludeActivationSpec) DeepCopyInto(out *IncludeActivationSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncludeActivationSpec.
func (in *IncludeActivationSpec) DeepCopy() *IncludeActivationSpec {
	if in == nil {
		return nil
	}
	out := new(IncludeActivationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncludeActivationStatus) DeepCopyInto(out *IncludeActivationStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncludeActivationStatus.
func (in *IncludeActivationStatus) DeepCopy() *IncludeActivationStatus {
	if in == nil {
		return nil
	}
	out := new(IncludeActivationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncludeInitParameters) DeepCopyInto(out *IncludeInitParameters) {
	*out = *in
	if in.ContractID != nil {
		in, out := &in.ContractID, &out.ContractID
		*out = new(string)
		**out = **in
	}
	if in.GroupID != nil {
		in, out := &in.GroupID, &out.GroupID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ProductID != nil {
		in, out := &in.ProductID, &out.ProductID
		*out = new(string)
		**out = **in
	}
	if in.RuleFormat != nil {
		in, out := &in.RuleFormat, &out.RuleFormat
		*out = new(string)
		**out = **in
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncludeInitParameters.
func (in *IncludeInitParameters) DeepCopy() *IncludeInitParameters {
	if in == nil {
		return nil
	}
	out := new(IncludeInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncludeList) DeepCopyInto(out *IncludeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Include, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncludeList.
func (in *IncludeList) DeepCopy() *IncludeList {
	if in == nil {
		return nil
	}
	out := new(IncludeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IncludeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncludeObservation) DeepCopyInto(out *IncludeObservation) {
	*out = *in
	if in.AssetID != nil {
		in, out := &in.AssetID, &out.AssetID
		*out = new(string)
		**out = **in
	}
	if in.ContractID != nil {
		in, out := &in.ContractID, &out.ContractID
		*out = new(string)
		**out = **in
	}
	if in.GroupID != nil {
		in, out := &in.GroupID, &out.GroupID
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LatestVersion != nil {
		in, out := &in.LatestVersion, &out.LatestVersion
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ProductID != nil {
		in, out := &in.ProductID, &out.ProductID
		*out = new(string)
		**out = **in
	}
	if in.ProductionVersion != nil {
		in, out := &in.ProductionVersion, &out.ProductionVersion
		*out = new(string)
		**out = **in
	}
	if in.RuleErrors != nil {
		in, out := &in.RuleErrors, &out.RuleErrors
		*out = new(string)
		**out = **in
	}
	if in.RuleFormat != nil {
		in, out := &in.RuleFormat, &out.RuleFormat
		*out = new(string)
		**out = **in
	}
	if in.RuleWarnings != nil {
		in, out := &in.RuleWarnings, &out.RuleWarnings
		*out = new(string)
		**out = **in
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = new(string)
		**out = **in
	}
	if in.StagingVersion != nil {
		in, out := &in.StagingVersion, &out.StagingVersion
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncludeObservation.
func (in *IncludeObservation) DeepCopy() *IncludeObservation {
	if in == nil {
		return nil
	}
	out := new(IncludeObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncludeParameters) DeepCopyInto(out *IncludeParameters) {
	*out = *in
	if in.ContractID != nil {
		in, out := &in.ContractID, &out.ContractID
		*out = new(string)
		**out = **in
	}
	if in.GroupID != nil {
		in, out := &in.GroupID, &out.GroupID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ProductID != nil {
		in, out := &in.ProductID, &out.ProductID
		*out = new(string)
		**out = **in
	}
	if in.RuleFormat != nil {
		in, out := &in.RuleFormat, &out.RuleFormat
		*out = new(string)
		**out = **in
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncludeParameters.
func (in *IncludeParameters) DeepCopy() *IncludeParameters {
	if in == nil {
		return nil
	}
	out := new(IncludeParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncludeSpec) DeepCopyInto(out *IncludeSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncludeSpec.
func (in *IncludeSpec) DeepCopy() *IncludeSpec {
	if in == nil {
		return nil
	}
	out := new(IncludeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncludeStatus) DeepCopyInto(out *IncludeStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncludeStatus.
func (in *IncludeStatus) DeepCopy() *IncludeStatus {
	if in == nil {
		return nil
	}
	out := new(IncludeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NoncomplianceReasonEmergencyInitParameters) DeepCopyInto(out *NoncomplianceReasonEmergencyInitParameters) {
	*out = *in
	if in.TicketID != nil {
		in, out := &in.TicketID, &out.TicketID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NoncomplianceReasonEmergencyInitParameters.
func (in *NoncomplianceReasonEmergencyInitParameters) DeepCopy() *NoncomplianceReasonEmergencyInitParameters {
	if in == nil {
		return nil
	}
	out := new(NoncomplianceReasonEmergencyInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NoncomplianceReasonEmergencyObservation) DeepCopyInto(out *NoncomplianceReasonEmergencyObservation) {
	*out = *in
	if in.TicketID != nil {
		in, out := &in.TicketID, &out.TicketID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NoncomplianceReasonEmergencyObservation.
func (in *NoncomplianceReasonEmergencyObservation) DeepCopy() *NoncomplianceReasonEmergencyObservation {
	if in == nil {
		return nil
	}
	out := new(NoncomplianceReasonEmergencyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NoncomplianceReasonEmergencyParameters) DeepCopyInto(out *NoncomplianceReasonEmergencyParameters) {
	*out = *in
	if in.TicketID != nil {
		in, out := &in.TicketID, &out.TicketID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NoncomplianceReasonEmergencyParameters.
func (in *NoncomplianceReasonEmergencyParameters) DeepCopy() *NoncomplianceReasonEmergencyParameters {
	if in == nil {
		return nil
	}
	out := new(NoncomplianceReasonEmergencyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NoncomplianceReasonNoProductionTrafficInitParameters) DeepCopyInto(out *NoncomplianceReasonNoProductionTrafficInitParameters) {
	*out = *in
	if in.TicketID != nil {
		in, out := &in.TicketID, &out.TicketID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NoncomplianceReasonNoProductionTrafficInitParameters.
func (in *NoncomplianceReasonNoProductionTrafficInitParameters) DeepCopy() *NoncomplianceReasonNoProductionTrafficInitParameters {
	if in == nil {
		return nil
	}
	out := new(NoncomplianceReasonNoProductionTrafficInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NoncomplianceReasonNoProductionTrafficObservation) DeepCopyInto(out *NoncomplianceReasonNoProductionTrafficObservation) {
	*out = *in
	if in.TicketID != nil {
		in, out := &in.TicketID, &out.TicketID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NoncomplianceReasonNoProductionTrafficObservation.
func (in *NoncomplianceReasonNoProductionTrafficObservation) DeepCopy() *NoncomplianceReasonNoProductionTrafficObservation {
	if in == nil {
		return nil
	}
	out := new(NoncomplianceReasonNoProductionTrafficObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NoncomplianceReasonNoProductionTrafficParameters) DeepCopyInto(out *NoncomplianceReasonNoProductionTrafficParameters) {
	*out = *in
	if in.TicketID != nil {
		in, out := &in.TicketID, &out.TicketID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NoncomplianceReasonNoProductionTrafficParameters.
func (in *NoncomplianceReasonNoProductionTrafficParameters) DeepCopy() *NoncomplianceReasonNoProductionTrafficParameters {
	if in == nil {
		return nil
	}
	out := new(NoncomplianceReasonNoProductionTrafficParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NoncomplianceReasonNoneInitParameters) DeepCopyInto(out *NoncomplianceReasonNoneInitParameters) {
	*out = *in
	if in.CustomerEmail != nil {
		in, out := &in.CustomerEmail, &out.CustomerEmail
		*out = new(string)
		**out = **in
	}
	if in.PeerReviewedBy != nil {
		in, out := &in.PeerReviewedBy, &out.PeerReviewedBy
		*out = new(string)
		**out = **in
	}
	if in.TicketID != nil {
		in, out := &in.TicketID, &out.TicketID
		*out = new(string)
		**out = **in
	}
	if in.UnitTested != nil {
		in, out := &in.UnitTested, &out.UnitTested
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NoncomplianceReasonNoneInitParameters.
func (in *NoncomplianceReasonNoneInitParameters) DeepCopy() *NoncomplianceReasonNoneInitParameters {
	if in == nil {
		return nil
	}
	out := new(NoncomplianceReasonNoneInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NoncomplianceReasonNoneObservation) DeepCopyInto(out *NoncomplianceReasonNoneObservation) {
	*out = *in
	if in.CustomerEmail != nil {
		in, out := &in.CustomerEmail, &out.CustomerEmail
		*out = new(string)
		**out = **in
	}
	if in.PeerReviewedBy != nil {
		in, out := &in.PeerReviewedBy, &out.PeerReviewedBy
		*out = new(string)
		**out = **in
	}
	if in.TicketID != nil {
		in, out := &in.TicketID, &out.TicketID
		*out = new(string)
		**out = **in
	}
	if in.UnitTested != nil {
		in, out := &in.UnitTested, &out.UnitTested
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NoncomplianceReasonNoneObservation.
func (in *NoncomplianceReasonNoneObservation) DeepCopy() *NoncomplianceReasonNoneObservation {
	if in == nil {
		return nil
	}
	out := new(NoncomplianceReasonNoneObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NoncomplianceReasonNoneParameters) DeepCopyInto(out *NoncomplianceReasonNoneParameters) {
	*out = *in
	if in.CustomerEmail != nil {
		in, out := &in.CustomerEmail, &out.CustomerEmail
		*out = new(string)
		**out = **in
	}
	if in.PeerReviewedBy != nil {
		in, out := &in.PeerReviewedBy, &out.PeerReviewedBy
		*out = new(string)
		**out = **in
	}
	if in.TicketID != nil {
		in, out := &in.TicketID, &out.TicketID
		*out = new(string)
		**out = **in
	}
	if in.UnitTested != nil {
		in, out := &in.UnitTested, &out.UnitTested
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NoncomplianceReasonNoneParameters.
func (in *NoncomplianceReasonNoneParameters) DeepCopy() *NoncomplianceReasonNoneParameters {
	if in == nil {
		return nil
	}
	out := new(NoncomplianceReasonNoneParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NoncomplianceReasonOtherInitParameters) DeepCopyInto(out *NoncomplianceReasonOtherInitParameters) {
	*out = *in
	if in.OtherNoncomplianceReason != nil {
		in, out := &in.OtherNoncomplianceReason, &out.OtherNoncomplianceReason
		*out = new(string)
		**out = **in
	}
	if in.TicketID != nil {
		in, out := &in.TicketID, &out.TicketID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NoncomplianceReasonOtherInitParameters.
func (in *NoncomplianceReasonOtherInitParameters) DeepCopy() *NoncomplianceReasonOtherInitParameters {
	if in == nil {
		return nil
	}
	out := new(NoncomplianceReasonOtherInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NoncomplianceReasonOtherObservation) DeepCopyInto(out *NoncomplianceReasonOtherObservation) {
	*out = *in
	if in.OtherNoncomplianceReason != nil {
		in, out := &in.OtherNoncomplianceReason, &out.OtherNoncomplianceReason
		*out = new(string)
		**out = **in
	}
	if in.TicketID != nil {
		in, out := &in.TicketID, &out.TicketID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NoncomplianceReasonOtherObservation.
func (in *NoncomplianceReasonOtherObservation) DeepCopy() *NoncomplianceReasonOtherObservation {
	if in == nil {
		return nil
	}
	out := new(NoncomplianceReasonOtherObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NoncomplianceReasonOtherParameters) DeepCopyInto(out *NoncomplianceReasonOtherParameters) {
	*out = *in
	if in.OtherNoncomplianceReason != nil {
		in, out := &in.OtherNoncomplianceReason, &out.OtherNoncomplianceReason
		*out = new(string)
		**out = **in
	}
	if in.TicketID != nil {
		in, out := &in.TicketID, &out.TicketID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NoncomplianceReasonOtherParameters.
func (in *NoncomplianceReasonOtherParameters) DeepCopy() *NoncomplianceReasonOtherParameters {
	if in == nil {
		return nil
	}
	out := new(NoncomplianceReasonOtherParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Property) DeepCopyInto(out *Property) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Property.
func (in *Property) DeepCopy() *Property {
	if in == nil {
		return nil
	}
	out := new(Property)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Property) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PropertyInitParameters) DeepCopyInto(out *PropertyInitParameters) {
	*out = *in
	if in.ContractID != nil {
		in, out := &in.ContractID, &out.ContractID
		*out = new(string)
		**out = **in
	}
	if in.GroupID != nil {
		in, out := &in.GroupID, &out.GroupID
		*out = new(string)
		**out = **in
	}
	if in.Hostnames != nil {
		in, out := &in.Hostnames, &out.Hostnames
		*out = make([]HostnamesInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ProductID != nil {
		in, out := &in.ProductID, &out.ProductID
		*out = new(string)
		**out = **in
	}
	if in.PropertyID != nil {
		in, out := &in.PropertyID, &out.PropertyID
		*out = new(string)
		**out = **in
	}
	if in.RuleFormat != nil {
		in, out := &in.RuleFormat, &out.RuleFormat
		*out = new(string)
		**out = **in
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = new(string)
		**out = **in
	}
	if in.UseHostnameBucket != nil {
		in, out := &in.UseHostnameBucket, &out.UseHostnameBucket
		*out = new(bool)
		**out = **in
	}
	if in.VersionNotes != nil {
		in, out := &in.VersionNotes, &out.VersionNotes
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PropertyInitParameters.
func (in *PropertyInitParameters) DeepCopy() *PropertyInitParameters {
	if in == nil {
		return nil
	}
	out := new(PropertyInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PropertyList) DeepCopyInto(out *PropertyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Property, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PropertyList.
func (in *PropertyList) DeepCopy() *PropertyList {
	if in == nil {
		return nil
	}
	out := new(PropertyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PropertyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PropertyObservation) DeepCopyInto(out *PropertyObservation) {
	*out = *in
	if in.AssetID != nil {
		in, out := &in.AssetID, &out.AssetID
		*out = new(string)
		**out = **in
	}
	if in.ContractID != nil {
		in, out := &in.ContractID, &out.ContractID
		*out = new(string)
		**out = **in
	}
	if in.GroupID != nil {
		in, out := &in.GroupID, &out.GroupID
		*out = new(string)
		**out = **in
	}
	if in.Hostnames != nil {
		in, out := &in.Hostnames, &out.Hostnames
		*out = make([]HostnamesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LatestVersion != nil {
		in, out := &in.LatestVersion, &out.LatestVersion
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ProductID != nil {
		in, out := &in.ProductID, &out.ProductID
		*out = new(string)
		**out = **in
	}
	if in.ProductionVersion != nil {
		in, out := &in.ProductionVersion, &out.ProductionVersion
		*out = new(float64)
		**out = **in
	}
	if in.PropertyID != nil {
		in, out := &in.PropertyID, &out.PropertyID
		*out = new(string)
		**out = **in
	}
	if in.ReadVersion != nil {
		in, out := &in.ReadVersion, &out.ReadVersion
		*out = new(float64)
		**out = **in
	}
	if in.RuleErrors != nil {
		in, out := &in.RuleErrors, &out.RuleErrors
		*out = make([]RuleErrorsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RuleFormat != nil {
		in, out := &in.RuleFormat, &out.RuleFormat
		*out = new(string)
		**out = **in
	}
	if in.RuleWarnings != nil {
		in, out := &in.RuleWarnings, &out.RuleWarnings
		*out = make([]RuleWarningsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = new(string)
		**out = **in
	}
	if in.StagingVersion != nil {
		in, out := &in.StagingVersion, &out.StagingVersion
		*out = new(float64)
		**out = **in
	}
	if in.UseHostnameBucket != nil {
		in, out := &in.UseHostnameBucket, &out.UseHostnameBucket
		*out = new(bool)
		**out = **in
	}
	if in.VersionNotes != nil {
		in, out := &in.VersionNotes, &out.VersionNotes
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PropertyObservation.
func (in *PropertyObservation) DeepCopy() *PropertyObservation {
	if in == nil {
		return nil
	}
	out := new(PropertyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PropertyParameters) DeepCopyInto(out *PropertyParameters) {
	*out = *in
	if in.ContractID != nil {
		in, out := &in.ContractID, &out.ContractID
		*out = new(string)
		**out = **in
	}
	if in.GroupID != nil {
		in, out := &in.GroupID, &out.GroupID
		*out = new(string)
		**out = **in
	}
	if in.Hostnames != nil {
		in, out := &in.Hostnames, &out.Hostnames
		*out = make([]HostnamesParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ProductID != nil {
		in, out := &in.ProductID, &out.ProductID
		*out = new(string)
		**out = **in
	}
	if in.PropertyID != nil {
		in, out := &in.PropertyID, &out.PropertyID
		*out = new(string)
		**out = **in
	}
	if in.RuleFormat != nil {
		in, out := &in.RuleFormat, &out.RuleFormat
		*out = new(string)
		**out = **in
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = new(string)
		**out = **in
	}
	if in.UseHostnameBucket != nil {
		in, out := &in.UseHostnameBucket, &out.UseHostnameBucket
		*out = new(bool)
		**out = **in
	}
	if in.VersionNotes != nil {
		in, out := &in.VersionNotes, &out.VersionNotes
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PropertyParameters.
func (in *PropertyParameters) DeepCopy() *PropertyParameters {
	if in == nil {
		return nil
	}
	out := new(PropertyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PropertySpec) DeepCopyInto(out *PropertySpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PropertySpec.
func (in *PropertySpec) DeepCopy() *PropertySpec {
	if in == nil {
		return nil
	}
	out := new(PropertySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PropertyStatus) DeepCopyInto(out *PropertyStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PropertyStatus.
func (in *PropertyStatus) DeepCopy() *PropertyStatus {
	if in == nil {
		return nil
	}
	out := new(PropertyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleErrorsInitParameters) DeepCopyInto(out *RuleErrorsInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleErrorsInitParameters.
func (in *RuleErrorsInitParameters) DeepCopy() *RuleErrorsInitParameters {
	if in == nil {
		return nil
	}
	out := new(RuleErrorsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleErrorsObservation) DeepCopyInto(out *RuleErrorsObservation) {
	*out = *in
	if in.BehaviorName != nil {
		in, out := &in.BehaviorName, &out.BehaviorName
		*out = new(string)
		**out = **in
	}
	if in.Detail != nil {
		in, out := &in.Detail, &out.Detail
		*out = new(string)
		**out = **in
	}
	if in.ErrorLocation != nil {
		in, out := &in.ErrorLocation, &out.ErrorLocation
		*out = new(string)
		**out = **in
	}
	if in.Instance != nil {
		in, out := &in.Instance, &out.Instance
		*out = new(string)
		**out = **in
	}
	if in.StatusCode != nil {
		in, out := &in.StatusCode, &out.StatusCode
		*out = new(float64)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleErrorsObservation.
func (in *RuleErrorsObservation) DeepCopy() *RuleErrorsObservation {
	if in == nil {
		return nil
	}
	out := new(RuleErrorsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleErrorsParameters) DeepCopyInto(out *RuleErrorsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleErrorsParameters.
func (in *RuleErrorsParameters) DeepCopy() *RuleErrorsParameters {
	if in == nil {
		return nil
	}
	out := new(RuleErrorsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleWarningsInitParameters) DeepCopyInto(out *RuleWarningsInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleWarningsInitParameters.
func (in *RuleWarningsInitParameters) DeepCopy() *RuleWarningsInitParameters {
	if in == nil {
		return nil
	}
	out := new(RuleWarningsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleWarningsObservation) DeepCopyInto(out *RuleWarningsObservation) {
	*out = *in
	if in.BehaviorName != nil {
		in, out := &in.BehaviorName, &out.BehaviorName
		*out = new(string)
		**out = **in
	}
	if in.Detail != nil {
		in, out := &in.Detail, &out.Detail
		*out = new(string)
		**out = **in
	}
	if in.ErrorLocation != nil {
		in, out := &in.ErrorLocation, &out.ErrorLocation
		*out = new(string)
		**out = **in
	}
	if in.Instance != nil {
		in, out := &in.Instance, &out.Instance
		*out = new(string)
		**out = **in
	}
	if in.StatusCode != nil {
		in, out := &in.StatusCode, &out.StatusCode
		*out = new(float64)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleWarningsObservation.
func (in *RuleWarningsObservation) DeepCopy() *RuleWarningsObservation {
	if in == nil {
		return nil
	}
	out := new(RuleWarningsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleWarningsParameters) DeepCopyInto(out *RuleWarningsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleWarningsParameters.
func (in *RuleWarningsParameters) DeepCopy() *RuleWarningsParameters {
	if in == nil {
		return nil
	}
	out := new(RuleWarningsParameters)
	in.DeepCopyInto(out)
	return out
}
