//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdminContactInitParameters) DeepCopyInto(out *AdminContactInitParameters) {
	*out = *in
	if in.AddressLineOne != nil {
		in, out := &in.AddressLineOne, &out.AddressLineOne
		*out = new(string)
		**out = **in
	}
	if in.AddressLineTwo != nil {
		in, out := &in.AddressLineTwo, &out.AddressLineTwo
		*out = new(string)
		**out = **in
	}
	if in.City != nil {
		in, out := &in.City, &out.City
		*out = new(string)
		**out = **in
	}
	if in.CountryCode != nil {
		in, out := &in.CountryCode, &out.CountryCode
		*out = new(string)
		**out = **in
	}
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(string)
		**out = **in
	}
	if in.FirstName != nil {
		in, out := &in.FirstName, &out.FirstName
		*out = new(string)
		**out = **in
	}
	if in.LastName != nil {
		in, out := &in.LastName, &out.LastName
		*out = new(string)
		**out = **in
	}
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = new(string)
		**out = **in
	}
	if in.Phone != nil {
		in, out := &in.Phone, &out.Phone
		*out = new(string)
		**out = **in
	}
	if in.PostalCode != nil {
		in, out := &in.PostalCode, &out.PostalCode
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdminContactInitParameters.
func (in *AdminContactInitParameters) DeepCopy() *AdminContactInitParameters {
	if in == nil {
		return nil
	}
	out := new(AdminContactInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdminContactObservation) DeepCopyInto(out *AdminContactObservation) {
	*out = *in
	if in.AddressLineOne != nil {
		in, out := &in.AddressLineOne, &out.AddressLineOne
		*out = new(string)
		**out = **in
	}
	if in.AddressLineTwo != nil {
		in, out := &in.AddressLineTwo, &out.AddressLineTwo
		*out = new(string)
		**out = **in
	}
	if in.City != nil {
		in, out := &in.City, &out.City
		*out = new(string)
		**out = **in
	}
	if in.CountryCode != nil {
		in, out := &in.CountryCode, &out.CountryCode
		*out = new(string)
		**out = **in
	}
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(string)
		**out = **in
	}
	if in.FirstName != nil {
		in, out := &in.FirstName, &out.FirstName
		*out = new(string)
		**out = **in
	}
	if in.LastName != nil {
		in, out := &in.LastName, &out.LastName
		*out = new(string)
		**out = **in
	}
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = new(string)
		**out = **in
	}
	if in.Phone != nil {
		in, out := &in.Phone, &out.Phone
		*out = new(string)
		**out = **in
	}
	if in.PostalCode != nil {
		in, out := &in.PostalCode, &out.PostalCode
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdminContactObservation.
func (in *AdminContactObservation) DeepCopy() *AdminContactObservation {
	if in == nil {
		return nil
	}
	out := new(AdminContactObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdminContactParameters) DeepCopyInto(out *AdminContactParameters) {
	*out = *in
	if in.AddressLineOne != nil {
		in, out := &in.AddressLineOne, &out.AddressLineOne
		*out = new(string)
		**out = **in
	}
	if in.AddressLineTwo != nil {
		in, out := &in.AddressLineTwo, &out.AddressLineTwo
		*out = new(string)
		**out = **in
	}
	if in.City != nil {
		in, out := &in.City, &out.City
		*out = new(string)
		**out = **in
	}
	if in.CountryCode != nil {
		in, out := &in.CountryCode, &out.CountryCode
		*out = new(string)
		**out = **in
	}
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(string)
		**out = **in
	}
	if in.FirstName != nil {
		in, out := &in.FirstName, &out.FirstName
		*out = new(string)
		**out = **in
	}
	if in.LastName != nil {
		in, out := &in.LastName, &out.LastName
		*out = new(string)
		**out = **in
	}
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = new(string)
		**out = **in
	}
	if in.Phone != nil {
		in, out := &in.Phone, &out.Phone
		*out = new(string)
		**out = **in
	}
	if in.PostalCode != nil {
		in, out := &in.PostalCode, &out.PostalCode
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdminContactParameters.
func (in *AdminContactParameters) DeepCopy() *AdminContactParameters {
	if in == nil {
		return nil
	}
	out := new(AdminContactParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientMutualAuthenticationInitParameters) DeepCopyInto(out *ClientMutualAuthenticationInitParameters) {
	*out = *in
	if in.OcspEnabled != nil {
		in, out := &in.OcspEnabled, &out.OcspEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SendCAListToClient != nil {
		in, out := &in.SendCAListToClient, &out.SendCAListToClient
		*out = new(bool)
		**out = **in
	}
	if in.SetID != nil {
		in, out := &in.SetID, &out.SetID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientMutualAuthenticationInitParameters.
func (in *ClientMutualAuthenticationInitParameters) DeepCopy() *ClientMutualAuthenticationInitParameters {
	if in == nil {
		return nil
	}
	out := new(ClientMutualAuthenticationInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientMutualAuthenticationObservation) DeepCopyInto(out *ClientMutualAuthenticationObservation) {
	*out = *in
	if in.OcspEnabled != nil {
		in, out := &in.OcspEnabled, &out.OcspEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SendCAListToClient != nil {
		in, out := &in.SendCAListToClient, &out.SendCAListToClient
		*out = new(bool)
		**out = **in
	}
	if in.SetID != nil {
		in, out := &in.SetID, &out.SetID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientMutualAuthenticationObservation.
func (in *ClientMutualAuthenticationObservation) DeepCopy() *ClientMutualAuthenticationObservation {
	if in == nil {
		return nil
	}
	out := new(ClientMutualAuthenticationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientMutualAuthenticationParameters) DeepCopyInto(out *ClientMutualAuthenticationParameters) {
	*out = *in
	if in.OcspEnabled != nil {
		in, out := &in.OcspEnabled, &out.OcspEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SendCAListToClient != nil {
		in, out := &in.SendCAListToClient, &out.SendCAListToClient
		*out = new(bool)
		**out = **in
	}
	if in.SetID != nil {
		in, out := &in.SetID, &out.SetID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientMutualAuthenticationParameters.
func (in *ClientMutualAuthenticationParameters) DeepCopy() *ClientMutualAuthenticationParameters {
	if in == nil {
		return nil
	}
	out := new(ClientMutualAuthenticationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CsrInitParameters) DeepCopyInto(out *CsrInitParameters) {
	*out = *in
	if in.City != nil {
		in, out := &in.City, &out.City
		*out = new(string)
		**out = **in
	}
	if in.CountryCode != nil {
		in, out := &in.CountryCode, &out.CountryCode
		*out = new(string)
		**out = **in
	}
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = new(string)
		**out = **in
	}
	if in.OrganizationalUnit != nil {
		in, out := &in.OrganizationalUnit, &out.OrganizationalUnit
		*out = new(string)
		**out = **in
	}
	if in.PreferredTrustChain != nil {
		in, out := &in.PreferredTrustChain, &out.PreferredTrustChain
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CsrInitParameters.
func (in *CsrInitParameters) DeepCopy() *CsrInitParameters {
	if in == nil {
		return nil
	}
	out := new(CsrInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CsrObservation) DeepCopyInto(out *CsrObservation) {
	*out = *in
	if in.City != nil {
		in, out := &in.City, &out.City
		*out = new(string)
		**out = **in
	}
	if in.CountryCode != nil {
		in, out := &in.CountryCode, &out.CountryCode
		*out = new(string)
		**out = **in
	}
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = new(string)
		**out = **in
	}
	if in.OrganizationalUnit != nil {
		in, out := &in.OrganizationalUnit, &out.OrganizationalUnit
		*out = new(string)
		**out = **in
	}
	if in.PreferredTrustChain != nil {
		in, out := &in.PreferredTrustChain, &out.PreferredTrustChain
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CsrObservation.
func (in *CsrObservation) DeepCopy() *CsrObservation {
	if in == nil {
		return nil
	}
	out := new(CsrObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CsrParameters) DeepCopyInto(out *CsrParameters) {
	*out = *in
	if in.City != nil {
		in, out := &in.City, &out.City
		*out = new(string)
		**out = **in
	}
	if in.CountryCode != nil {
		in, out := &in.CountryCode, &out.CountryCode
		*out = new(string)
		**out = **in
	}
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = new(string)
		**out = **in
	}
	if in.OrganizationalUnit != nil {
		in, out := &in.OrganizationalUnit, &out.OrganizationalUnit
		*out = new(string)
		**out = **in
	}
	if in.PreferredTrustChain != nil {
		in, out := &in.PreferredTrustChain, &out.PreferredTrustChain
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CsrParameters.
func (in *CsrParameters) DeepCopy() *CsrParameters {
	if in == nil {
		return nil
	}
	out := new(CsrParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSChallengesInitParameters) DeepCopyInto(out *DNSChallengesInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSChallengesInitParameters.
func (in *DNSChallengesInitParameters) DeepCopy() *DNSChallengesInitParameters {
	if in == nil {
		return nil
	}
	out := new(DNSChallengesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSChallengesObservation) DeepCopyInto(out *DNSChallengesObservation) {
	*out = *in
	if in.Domain != nil {
		in, out := &in.Domain, &out.Domain
		*out = new(string)
		**out = **in
	}
	if in.FullPath != nil {
		in, out := &in.FullPath, &out.FullPath
		*out = new(string)
		**out = **in
	}
	if in.ResponseBody != nil {
		in, out := &in.ResponseBody, &out.ResponseBody
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSChallengesObservation.
func (in *DNSChallengesObservation) DeepCopy() *DNSChallengesObservation {
	if in == nil {
		return nil
	}
	out := new(DNSChallengesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSChallengesParameters) DeepCopyInto(out *DNSChallengesParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSChallengesParameters.
func (in *DNSChallengesParameters) DeepCopy() *DNSChallengesParameters {
	if in == nil {
		return nil
	}
	out := new(DNSChallengesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DvEnrollment) DeepCopyInto(out *DvEnrollment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DvEnrollment.
func (in *DvEnrollment) DeepCopy() *DvEnrollment {
	if in == nil {
		return nil
	}
	out := new(DvEnrollment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DvEnrollment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DvEnrollmentInitParameters) DeepCopyInto(out *DvEnrollmentInitParameters) {
	*out = *in
	if in.AcknowledgePreVerificationWarnings != nil {
		in, out := &in.AcknowledgePreVerificationWarnings, &out.AcknowledgePreVerificationWarnings
		*out = new(bool)
		**out = **in
	}
	if in.AdminContact != nil {
		in, out := &in.AdminContact, &out.AdminContact
		*out = make([]AdminContactInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AllowDuplicateCommonName != nil {
		in, out := &in.AllowDuplicateCommonName, &out.AllowDuplicateCommonName
		*out = new(bool)
		**out = **in
	}
	if in.CertificateChainType != nil {
		in, out := &in.CertificateChainType, &out.CertificateChainType
		*out = new(string)
		**out = **in
	}
	if in.CommonName != nil {
		in, out := &in.CommonName, &out.CommonName
		*out = new(string)
		**out = **in
	}
	if in.ContractID != nil {
		in, out := &in.ContractID, &out.ContractID
		*out = new(string)
		**out = **in
	}
	if in.Csr != nil {
		in, out := &in.Csr, &out.Csr
		*out = make([]CsrInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NetworkConfiguration != nil {
		in, out := &in.NetworkConfiguration, &out.NetworkConfiguration
		*out = make([]NetworkConfigurationInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = make([]OrganizationInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Sans != nil {
		in, out := &in.Sans, &out.Sans
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SecureNetwork != nil {
		in, out := &in.SecureNetwork, &out.SecureNetwork
		*out = new(string)
		**out = **in
	}
	if in.SignatureAlgorithm != nil {
		in, out := &in.SignatureAlgorithm, &out.SignatureAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.SniOnly != nil {
		in, out := &in.SniOnly, &out.SniOnly
		*out = new(bool)
		**out = **in
	}
	if in.TechContact != nil {
		in, out := &in.TechContact, &out.TechContact
		*out = make([]TechContactInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DvEnrollmentInitParameters.
func (in *DvEnrollmentInitParameters) DeepCopy() *DvEnrollmentInitParameters {
	if in == nil {
		return nil
	}
	out := new(DvEnrollmentInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DvEnrollmentList) DeepCopyInto(out *DvEnrollmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DvEnrollment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DvEnrollmentList.
func (in *DvEnrollmentList) DeepCopy() *DvEnrollmentList {
	if in == nil {
		return nil
	}
	out := new(DvEnrollmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DvEnrollmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DvEnrollmentObservation) DeepCopyInto(out *DvEnrollmentObservation) {
	*out = *in
	if in.AcknowledgePreVerificationWarnings != nil {
		in, out := &in.AcknowledgePreVerificationWarnings, &out.AcknowledgePreVerificationWarnings
		*out = new(bool)
		**out = **in
	}
	if in.AdminContact != nil {
		in, out := &in.AdminContact, &out.AdminContact
		*out = make([]AdminContactObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AllowDuplicateCommonName != nil {
		in, out := &in.AllowDuplicateCommonName, &out.AllowDuplicateCommonName
		*out = new(bool)
		**out = **in
	}
	if in.CertificateChainType != nil {
		in, out := &in.CertificateChainType, &out.CertificateChainType
		*out = new(string)
		**out = **in
	}
	if in.CertificateType != nil {
		in, out := &in.CertificateType, &out.CertificateType
		*out = new(string)
		**out = **in
	}
	if in.CommonName != nil {
		in, out := &in.CommonName, &out.CommonName
		*out = new(string)
		**out = **in
	}
	if in.ContractID != nil {
		in, out := &in.ContractID, &out.ContractID
		*out = new(string)
		**out = **in
	}
	if in.Csr != nil {
		in, out := &in.Csr, &out.Csr
		*out = make([]CsrObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DNSChallenges != nil {
		in, out := &in.DNSChallenges, &out.DNSChallenges
		*out = make([]DNSChallengesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HTTPChallenges != nil {
		in, out := &in.HTTPChallenges, &out.HTTPChallenges
		*out = make([]HTTPChallengesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.NetworkConfiguration != nil {
		in, out := &in.NetworkConfiguration, &out.NetworkConfiguration
		*out = make([]NetworkConfigurationObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = make([]OrganizationObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RegistrationAuthority != nil {
		in, out := &in.RegistrationAuthority, &out.RegistrationAuthority
		*out = new(string)
		**out = **in
	}
	if in.Sans != nil {
		in, out := &in.Sans, &out.Sans
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SecureNetwork != nil {
		in, out := &in.SecureNetwork, &out.SecureNetwork
		*out = new(string)
		**out = **in
	}
	if in.SignatureAlgorithm != nil {
		in, out := &in.SignatureAlgorithm, &out.SignatureAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.SniOnly != nil {
		in, out := &in.SniOnly, &out.SniOnly
		*out = new(bool)
		**out = **in
	}
	if in.TechContact != nil {
		in, out := &in.TechContact, &out.TechContact
		*out = make([]TechContactObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ValidationType != nil {
		in, out := &in.ValidationType, &out.ValidationType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DvEnrollmentObservation.
func (in *DvEnrollmentObservation) DeepCopy() *DvEnrollmentObservation {
	if in == nil {
		return nil
	}
	out := new(DvEnrollmentObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DvEnrollmentParameters) DeepCopyInto(out *DvEnrollmentParameters) {
	*out = *in
	if in.AcknowledgePreVerificationWarnings != nil {
		in, out := &in.AcknowledgePreVerificationWarnings, &out.AcknowledgePreVerificationWarnings
		*out = new(bool)
		**out = **in
	}
	if in.AdminContact != nil {
		in, out := &in.AdminContact, &out.AdminContact
		*out = make([]AdminContactParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AllowDuplicateCommonName != nil {
		in, out := &in.AllowDuplicateCommonName, &out.AllowDuplicateCommonName
		*out = new(bool)
		**out = **in
	}
	if in.CertificateChainType != nil {
		in, out := &in.CertificateChainType, &out.CertificateChainType
		*out = new(string)
		**out = **in
	}
	if in.CommonName != nil {
		in, out := &in.CommonName, &out.CommonName
		*out = new(string)
		**out = **in
	}
	if in.ContractID != nil {
		in, out := &in.ContractID, &out.ContractID
		*out = new(string)
		**out = **in
	}
	if in.Csr != nil {
		in, out := &in.Csr, &out.Csr
		*out = make([]CsrParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NetworkConfiguration != nil {
		in, out := &in.NetworkConfiguration, &out.NetworkConfiguration
		*out = make([]NetworkConfigurationParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = make([]OrganizationParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Sans != nil {
		in, out := &in.Sans, &out.Sans
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SecureNetwork != nil {
		in, out := &in.SecureNetwork, &out.SecureNetwork
		*out = new(string)
		**out = **in
	}
	if in.SignatureAlgorithm != nil {
		in, out := &in.SignatureAlgorithm, &out.SignatureAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.SniOnly != nil {
		in, out := &in.SniOnly, &out.SniOnly
		*out = new(bool)
		**out = **in
	}
	if in.TechContact != nil {
		in, out := &in.TechContact, &out.TechContact
		*out = make([]TechContactParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DvEnrollmentParameters.
func (in *DvEnrollmentParameters) DeepCopy() *DvEnrollmentParameters {
	if in == nil {
		return nil
	}
	out := new(DvEnrollmentParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DvEnrollmentSpec) DeepCopyInto(out *DvEnrollmentSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DvEnrollmentSpec.
func (in *DvEnrollmentSpec) DeepCopy() *DvEnrollmentSpec {
	if in == nil {
		return nil
	}
	out := new(DvEnrollmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DvEnrollmentStatus) DeepCopyInto(out *DvEnrollmentStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DvEnrollmentStatus.
func (in *DvEnrollmentStatus) DeepCopy() *DvEnrollmentStatus {
	if in == nil {
		return nil
	}
	out := new(DvEnrollmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DvValidation) DeepCopyInto(out *DvValidation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DvValidation.
func (in *DvValidation) DeepCopy() *DvValidation {
	if in == nil {
		return nil
	}
	out := new(DvValidation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DvValidation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DvValidationInitParameters) DeepCopyInto(out *DvValidationInitParameters) {
	*out = *in
	if in.AcknowledgePostVerificationWarnings != nil {
		in, out := &in.AcknowledgePostVerificationWarnings, &out.AcknowledgePostVerificationWarnings
		*out = new(bool)
		**out = **in
	}
	if in.EnrollmentID != nil {
		in, out := &in.EnrollmentID, &out.EnrollmentID
		*out = new(float64)
		**out = **in
	}
	if in.Sans != nil {
		in, out := &in.Sans, &out.Sans
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DvValidationInitParameters.
func (in *DvValidationInitParameters) DeepCopy() *DvValidationInitParameters {
	if in == nil {
		return nil
	}
	out := new(DvValidationInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DvValidationList) DeepCopyInto(out *DvValidationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DvValidation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DvValidationList.
func (in *DvValidationList) DeepCopy() *DvValidationList {
	if in == nil {
		return nil
	}
	out := new(DvValidationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DvValidationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DvValidationObservation) DeepCopyInto(out *DvValidationObservation) {
	*out = *in
	if in.AcknowledgePostVerificationWarnings != nil {
		in, out := &in.AcknowledgePostVerificationWarnings, &out.AcknowledgePostVerificationWarnings
		*out = new(bool)
		**out = **in
	}
	if in.EnrollmentID != nil {
		in, out := &in.EnrollmentID, &out.EnrollmentID
		*out = new(float64)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Sans != nil {
		in, out := &in.Sans, &out.Sans
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DvValidationObservation.
func (in *DvValidationObservation) DeepCopy() *DvValidationObservation {
	if in == nil {
		return nil
	}
	out := new(DvValidationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DvValidationParameters) DeepCopyInto(out *DvValidationParameters) {
	*out = *in
	if in.AcknowledgePostVerificationWarnings != nil {
		in, out := &in.AcknowledgePostVerificationWarnings, &out.AcknowledgePostVerificationWarnings
		*out = new(bool)
		**out = **in
	}
	if in.EnrollmentID != nil {
		in, out := &in.EnrollmentID, &out.EnrollmentID
		*out = new(float64)
		**out = **in
	}
	if in.Sans != nil {
		in, out := &in.Sans, &out.Sans
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DvValidationParameters.
func (in *DvValidationParameters) DeepCopy() *DvValidationParameters {
	if in == nil {
		return nil
	}
	out := new(DvValidationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DvValidationSpec) DeepCopyInto(out *DvValidationSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DvValidationSpec.
func (in *DvValidationSpec) DeepCopy() *DvValidationSpec {
	if in == nil {
		return nil
	}
	out := new(DvValidationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DvValidationStatus) DeepCopyInto(out *DvValidationStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DvValidationStatus.
func (in *DvValidationStatus) DeepCopy() *DvValidationStatus {
	if in == nil {
		return nil
	}
	out := new(DvValidationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPChallengesInitParameters) DeepCopyInto(out *HTTPChallengesInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPChallengesInitParameters.
func (in *HTTPChallengesInitParameters) DeepCopy() *HTTPChallengesInitParameters {
	if in == nil {
		return nil
	}
	out := new(HTTPChallengesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPChallengesObservation) DeepCopyInto(out *HTTPChallengesObservation) {
	*out = *in
	if in.Domain != nil {
		in, out := &in.Domain, &out.Domain
		*out = new(string)
		**out = **in
	}
	if in.FullPath != nil {
		in, out := &in.FullPath, &out.FullPath
		*out = new(string)
		**out = **in
	}
	if in.ResponseBody != nil {
		in, out := &in.ResponseBody, &out.ResponseBody
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPChallengesObservation.
func (in *HTTPChallengesObservation) DeepCopy() *HTTPChallengesObservation {
	if in == nil {
		return nil
	}
	out := new(HTTPChallengesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPChallengesParameters) DeepCopyInto(out *HTTPChallengesParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPChallengesParameters.
func (in *HTTPChallengesParameters) DeepCopy() *HTTPChallengesParameters {
	if in == nil {
		return nil
	}
	out := new(HTTPChallengesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkConfigurationClientMutualAuthenticationInitParameters) DeepCopyInto(out *NetworkConfigurationClientMutualAuthenticationInitParameters) {
	*out = *in
	if in.OcspEnabled != nil {
		in, out := &in.OcspEnabled, &out.OcspEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SendCAListToClient != nil {
		in, out := &in.SendCAListToClient, &out.SendCAListToClient
		*out = new(bool)
		**out = **in
	}
	if in.SetID != nil {
		in, out := &in.SetID, &out.SetID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkConfigurationClientMutualAuthenticationInitParameters.
func (in *NetworkConfigurationClientMutualAuthenticationInitParameters) DeepCopy() *NetworkConfigurationClientMutualAuthenticationInitParameters {
	if in == nil {
		return nil
	}
	out := new(NetworkConfigurationClientMutualAuthenticationInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkConfigurationClientMutualAuthenticationObservation) DeepCopyInto(out *NetworkConfigurationClientMutualAuthenticationObservation) {
	*out = *in
	if in.OcspEnabled != nil {
		in, out := &in.OcspEnabled, &out.OcspEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SendCAListToClient != nil {
		in, out := &in.SendCAListToClient, &out.SendCAListToClient
		*out = new(bool)
		**out = **in
	}
	if in.SetID != nil {
		in, out := &in.SetID, &out.SetID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkConfigurationClientMutualAuthenticationObservation.
func (in *NetworkConfigurationClientMutualAuthenticationObservation) DeepCopy() *NetworkConfigurationClientMutualAuthenticationObservation {
	if in == nil {
		return nil
	}
	out := new(NetworkConfigurationClientMutualAuthenticationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkConfigurationClientMutualAuthenticationParameters) DeepCopyInto(out *NetworkConfigurationClientMutualAuthenticationParameters) {
	*out = *in
	if in.OcspEnabled != nil {
		in, out := &in.OcspEnabled, &out.OcspEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SendCAListToClient != nil {
		in, out := &in.SendCAListToClient, &out.SendCAListToClient
		*out = new(bool)
		**out = **in
	}
	if in.SetID != nil {
		in, out := &in.SetID, &out.SetID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkConfigurationClientMutualAuthenticationParameters.
func (in *NetworkConfigurationClientMutualAuthenticationParameters) DeepCopy() *NetworkConfigurationClientMutualAuthenticationParameters {
	if in == nil {
		return nil
	}
	out := new(NetworkConfigurationClientMutualAuthenticationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkConfigurationInitParameters) DeepCopyInto(out *NetworkConfigurationInitParameters) {
	*out = *in
	if in.ClientMutualAuthentication != nil {
		in, out := &in.ClientMutualAuthentication, &out.ClientMutualAuthentication
		*out = make([]ClientMutualAuthenticationInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CloneDNSNames != nil {
		in, out := &in.CloneDNSNames, &out.CloneDNSNames
		*out = new(bool)
		**out = **in
	}
	if in.DisallowedTLSVersions != nil {
		in, out := &in.DisallowedTLSVersions, &out.DisallowedTLSVersions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Geography != nil {
		in, out := &in.Geography, &out.Geography
		*out = new(string)
		**out = **in
	}
	if in.MustHaveCiphers != nil {
		in, out := &in.MustHaveCiphers, &out.MustHaveCiphers
		*out = new(string)
		**out = **in
	}
	if in.OcspStapling != nil {
		in, out := &in.OcspStapling, &out.OcspStapling
		*out = new(string)
		**out = **in
	}
	if in.PreferredCiphers != nil {
		in, out := &in.PreferredCiphers, &out.PreferredCiphers
		*out = new(string)
		**out = **in
	}
	if in.QuicEnabled != nil {
		in, out := &in.QuicEnabled, &out.QuicEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkConfigurationInitParameters.
func (in *NetworkConfigurationInitParameters) DeepCopy() *NetworkConfigurationInitParameters {
	if in == nil {
		return nil
	}
	out := new(NetworkConfigurationInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkConfigurationObservation) DeepCopyInto(out *NetworkConfigurationObservation) {
	*out = *in
	if in.ClientMutualAuthentication != nil {
		in, out := &in.ClientMutualAuthentication, &out.ClientMutualAuthentication
		*out = make([]ClientMutualAuthenticationObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CloneDNSNames != nil {
		in, out := &in.CloneDNSNames, &out.CloneDNSNames
		*out = new(bool)
		**out = **in
	}
	if in.DisallowedTLSVersions != nil {
		in, out := &in.DisallowedTLSVersions, &out.DisallowedTLSVersions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Geography != nil {
		in, out := &in.Geography, &out.Geography
		*out = new(string)
		**out = **in
	}
	if in.MustHaveCiphers != nil {
		in, out := &in.MustHaveCiphers, &out.MustHaveCiphers
		*out = new(string)
		**out = **in
	}
	if in.OcspStapling != nil {
		in, out := &in.OcspStapling, &out.OcspStapling
		*out = new(string)
		**out = **in
	}
	if in.PreferredCiphers != nil {
		in, out := &in.PreferredCiphers, &out.PreferredCiphers
		*out = new(string)
		**out = **in
	}
	if in.QuicEnabled != nil {
		in, out := &in.QuicEnabled, &out.QuicEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkConfigurationObservation.
func (in *NetworkConfigurationObservation) DeepCopy() *NetworkConfigurationObservation {
	if in == nil {
		return nil
	}
	out := new(NetworkConfigurationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkConfigurationParameters) DeepCopyInto(out *NetworkConfigurationParameters) {
	*out = *in
	if in.ClientMutualAuthentication != nil {
		in, out := &in.ClientMutualAuthentication, &out.ClientMutualAuthentication
		*out = make([]ClientMutualAuthenticationParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CloneDNSNames != nil {
		in, out := &in.CloneDNSNames, &out.CloneDNSNames
		*out = new(bool)
		**out = **in
	}
	if in.DisallowedTLSVersions != nil {
		in, out := &in.DisallowedTLSVersions, &out.DisallowedTLSVersions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Geography != nil {
		in, out := &in.Geography, &out.Geography
		*out = new(string)
		**out = **in
	}
	if in.MustHaveCiphers != nil {
		in, out := &in.MustHaveCiphers, &out.MustHaveCiphers
		*out = new(string)
		**out = **in
	}
	if in.OcspStapling != nil {
		in, out := &in.OcspStapling, &out.OcspStapling
		*out = new(string)
		**out = **in
	}
	if in.PreferredCiphers != nil {
		in, out := &in.PreferredCiphers, &out.PreferredCiphers
		*out = new(string)
		**out = **in
	}
	if in.QuicEnabled != nil {
		in, out := &in.QuicEnabled, &out.QuicEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkConfigurationParameters.
func (in *NetworkConfigurationParameters) DeepCopy() *NetworkConfigurationParameters {
	if in == nil {
		return nil
	}
	out := new(NetworkConfigurationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationInitParameters) DeepCopyInto(out *OrganizationInitParameters) {
	*out = *in
	if in.AddressLineOne != nil {
		in, out := &in.AddressLineOne, &out.AddressLineOne
		*out = new(string)
		**out = **in
	}
	if in.AddressLineTwo != nil {
		in, out := &in.AddressLineTwo, &out.AddressLineTwo
		*out = new(string)
		**out = **in
	}
	if in.City != nil {
		in, out := &in.City, &out.City
		*out = new(string)
		**out = **in
	}
	if in.CountryCode != nil {
		in, out := &in.CountryCode, &out.CountryCode
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Phone != nil {
		in, out := &in.Phone, &out.Phone
		*out = new(string)
		**out = **in
	}
	if in.PostalCode != nil {
		in, out := &in.PostalCode, &out.PostalCode
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationInitParameters.
func (in *OrganizationInitParameters) DeepCopy() *OrganizationInitParameters {
	if in == nil {
		return nil
	}
	out := new(OrganizationInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationObservation) DeepCopyInto(out *OrganizationObservation) {
	*out = *in
	if in.AddressLineOne != nil {
		in, out := &in.AddressLineOne, &out.AddressLineOne
		*out = new(string)
		**out = **in
	}
	if in.AddressLineTwo != nil {
		in, out := &in.AddressLineTwo, &out.AddressLineTwo
		*out = new(string)
		**out = **in
	}
	if in.City != nil {
		in, out := &in.City, &out.City
		*out = new(string)
		**out = **in
	}
	if in.CountryCode != nil {
		in, out := &in.CountryCode, &out.CountryCode
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Phone != nil {
		in, out := &in.Phone, &out.Phone
		*out = new(string)
		**out = **in
	}
	if in.PostalCode != nil {
		in, out := &in.PostalCode, &out.PostalCode
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationObservation.
func (in *OrganizationObservation) DeepCopy() *OrganizationObservation {
	if in == nil {
		return nil
	}
	out := new(OrganizationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationParameters) DeepCopyInto(out *OrganizationParameters) {
	*out = *in
	if in.AddressLineOne != nil {
		in, out := &in.AddressLineOne, &out.AddressLineOne
		*out = new(string)
		**out = **in
	}
	if in.AddressLineTwo != nil {
		in, out := &in.AddressLineTwo, &out.AddressLineTwo
		*out = new(string)
		**out = **in
	}
	if in.City != nil {
		in, out := &in.City, &out.City
		*out = new(string)
		**out = **in
	}
	if in.CountryCode != nil {
		in, out := &in.CountryCode, &out.CountryCode
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Phone != nil {
		in, out := &in.Phone, &out.Phone
		*out = new(string)
		**out = **in
	}
	if in.PostalCode != nil {
		in, out := &in.PostalCode, &out.PostalCode
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationParameters.
func (in *OrganizationParameters) DeepCopy() *OrganizationParameters {
	if in == nil {
		return nil
	}
	out := new(OrganizationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TechContactInitParameters) DeepCopyInto(out *TechContactInitParameters) {
	*out = *in
	if in.AddressLineOne != nil {
		in, out := &in.AddressLineOne, &out.AddressLineOne
		*out = new(string)
		**out = **in
	}
	if in.AddressLineTwo != nil {
		in, out := &in.AddressLineTwo, &out.AddressLineTwo
		*out = new(string)
		**out = **in
	}
	if in.City != nil {
		in, out := &in.City, &out.City
		*out = new(string)
		**out = **in
	}
	if in.CountryCode != nil {
		in, out := &in.CountryCode, &out.CountryCode
		*out = new(string)
		**out = **in
	}
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(string)
		**out = **in
	}
	if in.FirstName != nil {
		in, out := &in.FirstName, &out.FirstName
		*out = new(string)
		**out = **in
	}
	if in.LastName != nil {
		in, out := &in.LastName, &out.LastName
		*out = new(string)
		**out = **in
	}
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = new(string)
		**out = **in
	}
	if in.Phone != nil {
		in, out := &in.Phone, &out.Phone
		*out = new(string)
		**out = **in
	}
	if in.PostalCode != nil {
		in, out := &in.PostalCode, &out.PostalCode
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TechContactInitParameters.
func (in *TechContactInitParameters) DeepCopy() *TechContactInitParameters {
	if in == nil {
		return nil
	}
	out := new(TechContactInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TechContactObservation) DeepCopyInto(out *TechContactObservation) {
	*out = *in
	if in.AddressLineOne != nil {
		in, out := &in.AddressLineOne, &out.AddressLineOne
		*out = new(string)
		**out = **in
	}
	if in.AddressLineTwo != nil {
		in, out := &in.AddressLineTwo, &out.AddressLineTwo
		*out = new(string)
		**out = **in
	}
	if in.City != nil {
		in, out := &in.City, &out.City
		*out = new(string)
		**out = **in
	}
	if in.CountryCode != nil {
		in, out := &in.CountryCode, &out.CountryCode
		*out = new(string)
		**out = **in
	}
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(string)
		**out = **in
	}
	if in.FirstName != nil {
		in, out := &in.FirstName, &out.FirstName
		*out = new(string)
		**out = **in
	}
	if in.LastName != nil {
		in, out := &in.LastName, &out.LastName
		*out = new(string)
		**out = **in
	}
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = new(string)
		**out = **in
	}
	if in.Phone != nil {
		in, out := &in.Phone, &out.Phone
		*out = new(string)
		**out = **in
	}
	if in.PostalCode != nil {
		in, out := &in.PostalCode, &out.PostalCode
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TechContactObservation.
func (in *TechContactObservation) DeepCopy() *TechContactObservation {
	if in == nil {
		return nil
	}
	out := new(TechContactObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TechContactParameters) DeepCopyInto(out *TechContactParameters) {
	*out = *in
	if in.AddressLineOne != nil {
		in, out := &in.AddressLineOne, &out.AddressLineOne
		*out = new(string)
		**out = **in
	}
	if in.AddressLineTwo != nil {
		in, out := &in.AddressLineTwo, &out.AddressLineTwo
		*out = new(string)
		**out = **in
	}
	if in.City != nil {
		in, out := &in.City, &out.City
		*out = new(string)
		**out = **in
	}
	if in.CountryCode != nil {
		in, out := &in.CountryCode, &out.CountryCode
		*out = new(string)
		**out = **in
	}
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(string)
		**out = **in
	}
	if in.FirstName != nil {
		in, out := &in.FirstName, &out.FirstName
		*out = new(string)
		**out = **in
	}
	if in.LastName != nil {
		in, out := &in.LastName, &out.LastName
		*out = new(string)
		**out = **in
	}
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = new(string)
		**out = **in
	}
	if in.Phone != nil {
		in, out := &in.Phone, &out.Phone
		*out = new(string)
		**out = **in
	}
	if in.PostalCode != nil {
		in, out := &in.PostalCode, &out.PostalCode
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TechContactParameters.
func (in *TechContactParameters) DeepCopy() *TechContactParameters {
	if in == nil {
		return nil
	}
	out := new(TechContactParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThirdPartyEnrollment) DeepCopyInto(out *ThirdPartyEnrollment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThirdPartyEnrollment.
func (in *ThirdPartyEnrollment) DeepCopy() *ThirdPartyEnrollment {
	if in == nil {
		return nil
	}
	out := new(ThirdPartyEnrollment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ThirdPartyEnrollment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThirdPartyEnrollmentAdminContactInitParameters) DeepCopyInto(out *ThirdPartyEnrollmentAdminContactInitParameters) {
	*out = *in
	if in.AddressLineOne != nil {
		in, out := &in.AddressLineOne, &out.AddressLineOne
		*out = new(string)
		**out = **in
	}
	if in.AddressLineTwo != nil {
		in, out := &in.AddressLineTwo, &out.AddressLineTwo
		*out = new(string)
		**out = **in
	}
	if in.City != nil {
		in, out := &in.City, &out.City
		*out = new(string)
		**out = **in
	}
	if in.CountryCode != nil {
		in, out := &in.CountryCode, &out.CountryCode
		*out = new(string)
		**out = **in
	}
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(string)
		**out = **in
	}
	if in.FirstName != nil {
		in, out := &in.FirstName, &out.FirstName
		*out = new(string)
		**out = **in
	}
	if in.LastName != nil {
		in, out := &in.LastName, &out.LastName
		*out = new(string)
		**out = **in
	}
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = new(string)
		**out = **in
	}
	if in.Phone != nil {
		in, out := &in.Phone, &out.Phone
		*out = new(string)
		**out = **in
	}
	if in.PostalCode != nil {
		in, out := &in.PostalCode, &out.PostalCode
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThirdPartyEnrollmentAdminContactInitParameters.
func (in *ThirdPartyEnrollmentAdminContactInitParameters) DeepCopy() *ThirdPartyEnrollmentAdminContactInitParameters {
	if in == nil {
		return nil
	}
	out := new(ThirdPartyEnrollmentAdminContactInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThirdPartyEnrollmentAdminContactObservation) DeepCopyInto(out *ThirdPartyEnrollmentAdminContactObservation) {
	*out = *in
	if in.AddressLineOne != nil {
		in, out := &in.AddressLineOne, &out.AddressLineOne
		*out = new(string)
		**out = **in
	}
	if in.AddressLineTwo != nil {
		in, out := &in.AddressLineTwo, &out.AddressLineTwo
		*out = new(string)
		**out = **in
	}
	if in.City != nil {
		in, out := &in.City, &out.City
		*out = new(string)
		**out = **in
	}
	if in.CountryCode != nil {
		in, out := &in.CountryCode, &out.CountryCode
		*out = new(string)
		**out = **in
	}
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(string)
		**out = **in
	}
	if in.FirstName != nil {
		in, out := &in.FirstName, &out.FirstName
		*out = new(string)
		**out = **in
	}
	if in.LastName != nil {
		in, out := &in.LastName, &out.LastName
		*out = new(string)
		**out = **in
	}
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = new(string)
		**out = **in
	}
	if in.Phone != nil {
		in, out := &in.Phone, &out.Phone
		*out = new(string)
		**out = **in
	}
	if in.PostalCode != nil {
		in, out := &in.PostalCode, &out.PostalCode
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThirdPartyEnrollmentAdminContactObservation.
func (in *ThirdPartyEnrollmentAdminContactObservation) DeepCopy() *ThirdPartyEnrollmentAdminContactObservation {
	if in == nil {
		return nil
	}
	out := new(ThirdPartyEnrollmentAdminContactObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThirdPartyEnrollmentAdminContactParameters) DeepCopyInto(out *ThirdPartyEnrollmentAdminContactParameters) {
	*out = *in
	if in.AddressLineOne != nil {
		in, out := &in.AddressLineOne, &out.AddressLineOne
		*out = new(string)
		**out = **in
	}
	if in.AddressLineTwo != nil {
		in, out := &in.AddressLineTwo, &out.AddressLineTwo
		*out = new(string)
		**out = **in
	}
	if in.City != nil {
		in, out := &in.City, &out.City
		*out = new(string)
		**out = **in
	}
	if in.CountryCode != nil {
		in, out := &in.CountryCode, &out.CountryCode
		*out = new(string)
		**out = **in
	}
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(string)
		**out = **in
	}
	if in.FirstName != nil {
		in, out := &in.FirstName, &out.FirstName
		*out = new(string)
		**out = **in
	}
	if in.LastName != nil {
		in, out := &in.LastName, &out.LastName
		*out = new(string)
		**out = **in
	}
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = new(string)
		**out = **in
	}
	if in.Phone != nil {
		in, out := &in.Phone, &out.Phone
		*out = new(string)
		**out = **in
	}
	if in.PostalCode != nil {
		in, out := &in.PostalCode, &out.PostalCode
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThirdPartyEnrollmentAdminContactParameters.
func (in *ThirdPartyEnrollmentAdminContactParameters) DeepCopy() *ThirdPartyEnrollmentAdminContactParameters {
	if in == nil {
		return nil
	}
	out := new(ThirdPartyEnrollmentAdminContactParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThirdPartyEnrollmentCsrInitParameters) DeepCopyInto(out *ThirdPartyEnrollmentCsrInitParameters) {
	*out = *in
	if in.City != nil {
		in, out := &in.City, &out.City
		*out = new(string)
		**out = **in
	}
	if in.CountryCode != nil {
		in, out := &in.CountryCode, &out.CountryCode
		*out = new(string)
		**out = **in
	}
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = new(string)
		**out = **in
	}
	if in.OrganizationalUnit != nil {
		in, out := &in.OrganizationalUnit, &out.OrganizationalUnit
		*out = new(string)
		**out = **in
	}
	if in.PreferredTrustChain != nil {
		in, out := &in.PreferredTrustChain, &out.PreferredTrustChain
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThirdPartyEnrollmentCsrInitParameters.
func (in *ThirdPartyEnrollmentCsrInitParameters) DeepCopy() *ThirdPartyEnrollmentCsrInitParameters {
	if in == nil {
		return nil
	}
	out := new(ThirdPartyEnrollmentCsrInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThirdPartyEnrollmentCsrObservation) DeepCopyInto(out *ThirdPartyEnrollmentCsrObservation) {
	*out = *in
	if in.City != nil {
		in, out := &in.City, &out.City
		*out = new(string)
		**out = **in
	}
	if in.CountryCode != nil {
		in, out := &in.CountryCode, &out.CountryCode
		*out = new(string)
		**out = **in
	}
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = new(string)
		**out = **in
	}
	if in.OrganizationalUnit != nil {
		in, out := &in.OrganizationalUnit, &out.OrganizationalUnit
		*out = new(string)
		**out = **in
	}
	if in.PreferredTrustChain != nil {
		in, out := &in.PreferredTrustChain, &out.PreferredTrustChain
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThirdPartyEnrollmentCsrObservation.
func (in *ThirdPartyEnrollmentCsrObservation) DeepCopy() *ThirdPartyEnrollmentCsrObservation {
	if in == nil {
		return nil
	}
	out := new(ThirdPartyEnrollmentCsrObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThirdPartyEnrollmentCsrParameters) DeepCopyInto(out *ThirdPartyEnrollmentCsrParameters) {
	*out = *in
	if in.City != nil {
		in, out := &in.City, &out.City
		*out = new(string)
		**out = **in
	}
	if in.CountryCode != nil {
		in, out := &in.CountryCode, &out.CountryCode
		*out = new(string)
		**out = **in
	}
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = new(string)
		**out = **in
	}
	if in.OrganizationalUnit != nil {
		in, out := &in.OrganizationalUnit, &out.OrganizationalUnit
		*out = new(string)
		**out = **in
	}
	if in.PreferredTrustChain != nil {
		in, out := &in.PreferredTrustChain, &out.PreferredTrustChain
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThirdPartyEnrollmentCsrParameters.
func (in *ThirdPartyEnrollmentCsrParameters) DeepCopy() *ThirdPartyEnrollmentCsrParameters {
	if in == nil {
		return nil
	}
	out := new(ThirdPartyEnrollmentCsrParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThirdPartyEnrollmentInitParameters) DeepCopyInto(out *ThirdPartyEnrollmentInitParameters) {
	*out = *in
	if in.AcknowledgePreVerificationWarnings != nil {
		in, out := &in.AcknowledgePreVerificationWarnings, &out.AcknowledgePreVerificationWarnings
		*out = new(bool)
		**out = **in
	}
	if in.AdminContact != nil {
		in, out := &in.AdminContact, &out.AdminContact
		*out = make([]ThirdPartyEnrollmentAdminContactInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AllowDuplicateCommonName != nil {
		in, out := &in.AllowDuplicateCommonName, &out.AllowDuplicateCommonName
		*out = new(bool)
		**out = **in
	}
	if in.AutoApproveWarnings != nil {
		in, out := &in.AutoApproveWarnings, &out.AutoApproveWarnings
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.CertificateChainType != nil {
		in, out := &in.CertificateChainType, &out.CertificateChainType
		*out = new(string)
		**out = **in
	}
	if in.ChangeManagement != nil {
		in, out := &in.ChangeManagement, &out.ChangeManagement
		*out = new(bool)
		**out = **in
	}
	if in.CommonName != nil {
		in, out := &in.CommonName, &out.CommonName
		*out = new(string)
		**out = **in
	}
	if in.ContractID != nil {
		in, out := &in.ContractID, &out.ContractID
		*out = new(string)
		**out = **in
	}
	if in.Csr != nil {
		in, out := &in.Csr, &out.Csr
		*out = make([]ThirdPartyEnrollmentCsrInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExcludeSans != nil {
		in, out := &in.ExcludeSans, &out.ExcludeSans
		*out = new(bool)
		**out = **in
	}
	if in.NetworkConfiguration != nil {
		in, out := &in.NetworkConfiguration, &out.NetworkConfiguration
		*out = make([]ThirdPartyEnrollmentNetworkConfigurationInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = make([]ThirdPartyEnrollmentOrganizationInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Sans != nil {
		in, out := &in.Sans, &out.Sans
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SecureNetwork != nil {
		in, out := &in.SecureNetwork, &out.SecureNetwork
		*out = new(string)
		**out = **in
	}
	if in.SignatureAlgorithm != nil {
		in, out := &in.SignatureAlgorithm, &out.SignatureAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.SniOnly != nil {
		in, out := &in.SniOnly, &out.SniOnly
		*out = new(bool)
		**out = **in
	}
	if in.TechContact != nil {
		in, out := &in.TechContact, &out.TechContact
		*out = make([]ThirdPartyEnrollmentTechContactInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThirdPartyEnrollmentInitParameters.
func (in *ThirdPartyEnrollmentInitParameters) DeepCopy() *ThirdPartyEnrollmentInitParameters {
	if in == nil {
		return nil
	}
	out := new(ThirdPartyEnrollmentInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThirdPartyEnrollmentList) DeepCopyInto(out *ThirdPartyEnrollmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ThirdPartyEnrollment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThirdPartyEnrollmentList.
func (in *ThirdPartyEnrollmentList) DeepCopy() *ThirdPartyEnrollmentList {
	if in == nil {
		return nil
	}
	out := new(ThirdPartyEnrollmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ThirdPartyEnrollmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThirdPartyEnrollmentNetworkConfigurationInitParameters) DeepCopyInto(out *ThirdPartyEnrollmentNetworkConfigurationInitParameters) {
	*out = *in
	if in.ClientMutualAuthentication != nil {
		in, out := &in.ClientMutualAuthentication, &out.ClientMutualAuthentication
		*out = make([]NetworkConfigurationClientMutualAuthenticationInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CloneDNSNames != nil {
		in, out := &in.CloneDNSNames, &out.CloneDNSNames
		*out = new(bool)
		**out = **in
	}
	if in.DisallowedTLSVersions != nil {
		in, out := &in.DisallowedTLSVersions, &out.DisallowedTLSVersions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Geography != nil {
		in, out := &in.Geography, &out.Geography
		*out = new(string)
		**out = **in
	}
	if in.MustHaveCiphers != nil {
		in, out := &in.MustHaveCiphers, &out.MustHaveCiphers
		*out = new(string)
		**out = **in
	}
	if in.OcspStapling != nil {
		in, out := &in.OcspStapling, &out.OcspStapling
		*out = new(string)
		**out = **in
	}
	if in.PreferredCiphers != nil {
		in, out := &in.PreferredCiphers, &out.PreferredCiphers
		*out = new(string)
		**out = **in
	}
	if in.QuicEnabled != nil {
		in, out := &in.QuicEnabled, &out.QuicEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThirdPartyEnrollmentNetworkConfigurationInitParameters.
func (in *ThirdPartyEnrollmentNetworkConfigurationInitParameters) DeepCopy() *ThirdPartyEnrollmentNetworkConfigurationInitParameters {
	if in == nil {
		return nil
	}
	out := new(ThirdPartyEnrollmentNetworkConfigurationInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThirdPartyEnrollmentNetworkConfigurationObservation) DeepCopyInto(out *ThirdPartyEnrollmentNetworkConfigurationObservation) {
	*out = *in
	if in.ClientMutualAuthentication != nil {
		in, out := &in.ClientMutualAuthentication, &out.ClientMutualAuthentication
		*out = make([]NetworkConfigurationClientMutualAuthenticationObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CloneDNSNames != nil {
		in, out := &in.CloneDNSNames, &out.CloneDNSNames
		*out = new(bool)
		**out = **in
	}
	if in.DisallowedTLSVersions != nil {
		in, out := &in.DisallowedTLSVersions, &out.DisallowedTLSVersions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Geography != nil {
		in, out := &in.Geography, &out.Geography
		*out = new(string)
		**out = **in
	}
	if in.MustHaveCiphers != nil {
		in, out := &in.MustHaveCiphers, &out.MustHaveCiphers
		*out = new(string)
		**out = **in
	}
	if in.OcspStapling != nil {
		in, out := &in.OcspStapling, &out.OcspStapling
		*out = new(string)
		**out = **in
	}
	if in.PreferredCiphers != nil {
		in, out := &in.PreferredCiphers, &out.PreferredCiphers
		*out = new(string)
		**out = **in
	}
	if in.QuicEnabled != nil {
		in, out := &in.QuicEnabled, &out.QuicEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThirdPartyEnrollmentNetworkConfigurationObservation.
func (in *ThirdPartyEnrollmentNetworkConfigurationObservation) DeepCopy() *ThirdPartyEnrollmentNetworkConfigurationObservation {
	if in == nil {
		return nil
	}
	out := new(ThirdPartyEnrollmentNetworkConfigurationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThirdPartyEnrollmentNetworkConfigurationParameters) DeepCopyInto(out *ThirdPartyEnrollmentNetworkConfigurationParameters) {
	*out = *in
	if in.ClientMutualAuthentication != nil {
		in, out := &in.ClientMutualAuthentication, &out.ClientMutualAuthentication
		*out = make([]NetworkConfigurationClientMutualAuthenticationParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CloneDNSNames != nil {
		in, out := &in.CloneDNSNames, &out.CloneDNSNames
		*out = new(bool)
		**out = **in
	}
	if in.DisallowedTLSVersions != nil {
		in, out := &in.DisallowedTLSVersions, &out.DisallowedTLSVersions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Geography != nil {
		in, out := &in.Geography, &out.Geography
		*out = new(string)
		**out = **in
	}
	if in.MustHaveCiphers != nil {
		in, out := &in.MustHaveCiphers, &out.MustHaveCiphers
		*out = new(string)
		**out = **in
	}
	if in.OcspStapling != nil {
		in, out := &in.OcspStapling, &out.OcspStapling
		*out = new(string)
		**out = **in
	}
	if in.PreferredCiphers != nil {
		in, out := &in.PreferredCiphers, &out.PreferredCiphers
		*out = new(string)
		**out = **in
	}
	if in.QuicEnabled != nil {
		in, out := &in.QuicEnabled, &out.QuicEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThirdPartyEnrollmentNetworkConfigurationParameters.
func (in *ThirdPartyEnrollmentNetworkConfigurationParameters) DeepCopy() *ThirdPartyEnrollmentNetworkConfigurationParameters {
	if in == nil {
		return nil
	}
	out := new(ThirdPartyEnrollmentNetworkConfigurationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThirdPartyEnrollmentObservation) DeepCopyInto(out *ThirdPartyEnrollmentObservation) {
	*out = *in
	if in.AcknowledgePreVerificationWarnings != nil {
		in, out := &in.AcknowledgePreVerificationWarnings, &out.AcknowledgePreVerificationWarnings
		*out = new(bool)
		**out = **in
	}
	if in.AdminContact != nil {
		in, out := &in.AdminContact, &out.AdminContact
		*out = make([]ThirdPartyEnrollmentAdminContactObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AllowDuplicateCommonName != nil {
		in, out := &in.AllowDuplicateCommonName, &out.AllowDuplicateCommonName
		*out = new(bool)
		**out = **in
	}
	if in.AutoApproveWarnings != nil {
		in, out := &in.AutoApproveWarnings, &out.AutoApproveWarnings
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.CertificateChainType != nil {
		in, out := &in.CertificateChainType, &out.CertificateChainType
		*out = new(string)
		**out = **in
	}
	if in.ChangeManagement != nil {
		in, out := &in.ChangeManagement, &out.ChangeManagement
		*out = new(bool)
		**out = **in
	}
	if in.CommonName != nil {
		in, out := &in.CommonName, &out.CommonName
		*out = new(string)
		**out = **in
	}
	if in.ContractID != nil {
		in, out := &in.ContractID, &out.ContractID
		*out = new(string)
		**out = **in
	}
	if in.Csr != nil {
		in, out := &in.Csr, &out.Csr
		*out = make([]ThirdPartyEnrollmentCsrObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExcludeSans != nil {
		in, out := &in.ExcludeSans, &out.ExcludeSans
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.NetworkConfiguration != nil {
		in, out := &in.NetworkConfiguration, &out.NetworkConfiguration
		*out = make([]ThirdPartyEnrollmentNetworkConfigurationObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = make([]ThirdPartyEnrollmentOrganizationObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Sans != nil {
		in, out := &in.Sans, &out.Sans
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SecureNetwork != nil {
		in, out := &in.SecureNetwork, &out.SecureNetwork
		*out = new(string)
		**out = **in
	}
	if in.SignatureAlgorithm != nil {
		in, out := &in.SignatureAlgorithm, &out.SignatureAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.SniOnly != nil {
		in, out := &in.SniOnly, &out.SniOnly
		*out = new(bool)
		**out = **in
	}
	if in.TechContact != nil {
		in, out := &in.TechContact, &out.TechContact
		*out = make([]ThirdPartyEnrollmentTechContactObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThirdPartyEnrollmentObservation.
func (in *ThirdPartyEnrollmentObservation) DeepCopy() *ThirdPartyEnrollmentObservation {
	if in == nil {
		return nil
	}
	out := new(ThirdPartyEnrollmentObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThirdPartyEnrollmentOrganizationInitParameters) DeepCopyInto(out *ThirdPartyEnrollmentOrganizationInitParameters) {
	*out = *in
	if in.AddressLineOne != nil {
		in, out := &in.AddressLineOne, &out.AddressLineOne
		*out = new(string)
		**out = **in
	}
	if in.AddressLineTwo != nil {
		in, out := &in.AddressLineTwo, &out.AddressLineTwo
		*out = new(string)
		**out = **in
	}
	if in.City != nil {
		in, out := &in.City, &out.City
		*out = new(string)
		**out = **in
	}
	if in.CountryCode != nil {
		in, out := &in.CountryCode, &out.CountryCode
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Phone != nil {
		in, out := &in.Phone, &out.Phone
		*out = new(string)
		**out = **in
	}
	if in.PostalCode != nil {
		in, out := &in.PostalCode, &out.PostalCode
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThirdPartyEnrollmentOrganizationInitParameters.
func (in *ThirdPartyEnrollmentOrganizationInitParameters) DeepCopy() *ThirdPartyEnrollmentOrganizationInitParameters {
	if in == nil {
		return nil
	}
	out := new(ThirdPartyEnrollmentOrganizationInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThirdPartyEnrollmentOrganizationObservation) DeepCopyInto(out *ThirdPartyEnrollmentOrganizationObservation) {
	*out = *in
	if in.AddressLineOne != nil {
		in, out := &in.AddressLineOne, &out.AddressLineOne
		*out = new(string)
		**out = **in
	}
	if in.AddressLineTwo != nil {
		in, out := &in.AddressLineTwo, &out.AddressLineTwo
		*out = new(string)
		**out = **in
	}
	if in.City != nil {
		in, out := &in.City, &out.City
		*out = new(string)
		**out = **in
	}
	if in.CountryCode != nil {
		in, out := &in.CountryCode, &out.CountryCode
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Phone != nil {
		in, out := &in.Phone, &out.Phone
		*out = new(string)
		**out = **in
	}
	if in.PostalCode != nil {
		in, out := &in.PostalCode, &out.PostalCode
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThirdPartyEnrollmentOrganizationObservation.
func (in *ThirdPartyEnrollmentOrganizationObservation) DeepCopy() *ThirdPartyEnrollmentOrganizationObservation {
	if in == nil {
		return nil
	}
	out := new(ThirdPartyEnrollmentOrganizationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThirdPartyEnrollmentOrganizationParameters) DeepCopyInto(out *ThirdPartyEnrollmentOrganizationParameters) {
	*out = *in
	if in.AddressLineOne != nil {
		in, out := &in.AddressLineOne, &out.AddressLineOne
		*out = new(string)
		**out = **in
	}
	if in.AddressLineTwo != nil {
		in, out := &in.AddressLineTwo, &out.AddressLineTwo
		*out = new(string)
		**out = **in
	}
	if in.City != nil {
		in, out := &in.City, &out.City
		*out = new(string)
		**out = **in
	}
	if in.CountryCode != nil {
		in, out := &in.CountryCode, &out.CountryCode
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Phone != nil {
		in, out := &in.Phone, &out.Phone
		*out = new(string)
		**out = **in
	}
	if in.PostalCode != nil {
		in, out := &in.PostalCode, &out.PostalCode
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThirdPartyEnrollmentOrganizationParameters.
func (in *ThirdPartyEnrollmentOrganizationParameters) DeepCopy() *ThirdPartyEnrollmentOrganizationParameters {
	if in == nil {
		return nil
	}
	out := new(ThirdPartyEnrollmentOrganizationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThirdPartyEnrollmentParameters) DeepCopyInto(out *ThirdPartyEnrollmentParameters) {
	*out = *in
	if in.AcknowledgePreVerificationWarnings != nil {
		in, out := &in.AcknowledgePreVerificationWarnings, &out.AcknowledgePreVerificationWarnings
		*out = new(bool)
		**out = **in
	}
	if in.AdminContact != nil {
		in, out := &in.AdminContact, &out.AdminContact
		*out = make([]ThirdPartyEnrollmentAdminContactParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AllowDuplicateCommonName != nil {
		in, out := &in.AllowDuplicateCommonName, &out.AllowDuplicateCommonName
		*out = new(bool)
		**out = **in
	}
	if in.AutoApproveWarnings != nil {
		in, out := &in.AutoApproveWarnings, &out.AutoApproveWarnings
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.CertificateChainType != nil {
		in, out := &in.CertificateChainType, &out.CertificateChainType
		*out = new(string)
		**out = **in
	}
	if in.ChangeManagement != nil {
		in, out := &in.ChangeManagement, &out.ChangeManagement
		*out = new(bool)
		**out = **in
	}
	if in.CommonName != nil {
		in, out := &in.CommonName, &out.CommonName
		*out = new(string)
		**out = **in
	}
	if in.ContractID != nil {
		in, out := &in.ContractID, &out.ContractID
		*out = new(string)
		**out = **in
	}
	if in.Csr != nil {
		in, out := &in.Csr, &out.Csr
		*out = make([]ThirdPartyEnrollmentCsrParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExcludeSans != nil {
		in, out := &in.ExcludeSans, &out.ExcludeSans
		*out = new(bool)
		**out = **in
	}
	if in.NetworkConfiguration != nil {
		in, out := &in.NetworkConfiguration, &out.NetworkConfiguration
		*out = make([]ThirdPartyEnrollmentNetworkConfigurationParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = make([]ThirdPartyEnrollmentOrganizationParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Sans != nil {
		in, out := &in.Sans, &out.Sans
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SecureNetwork != nil {
		in, out := &in.SecureNetwork, &out.SecureNetwork
		*out = new(string)
		**out = **in
	}
	if in.SignatureAlgorithm != nil {
		in, out := &in.SignatureAlgorithm, &out.SignatureAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.SniOnly != nil {
		in, out := &in.SniOnly, &out.SniOnly
		*out = new(bool)
		**out = **in
	}
	if in.TechContact != nil {
		in, out := &in.TechContact, &out.TechContact
		*out = make([]ThirdPartyEnrollmentTechContactParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThirdPartyEnrollmentParameters.
func (in *ThirdPartyEnrollmentParameters) DeepCopy() *ThirdPartyEnrollmentParameters {
	if in == nil {
		return nil
	}
	out := new(ThirdPartyEnrollmentParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThirdPartyEnrollmentSpec) DeepCopyInto(out *ThirdPartyEnrollmentSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThirdPartyEnrollmentSpec.
func (in *ThirdPartyEnrollmentSpec) DeepCopy() *ThirdPartyEnrollmentSpec {
	if in == nil {
		return nil
	}
	out := new(ThirdPartyEnrollmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThirdPartyEnrollmentStatus) DeepCopyInto(out *ThirdPartyEnrollmentStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThirdPartyEnrollmentStatus.
func (in *ThirdPartyEnrollmentStatus) DeepCopy() *ThirdPartyEnrollmentStatus {
	if in == nil {
		return nil
	}
	out := new(ThirdPartyEnrollmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThirdPartyEnrollmentTechContactInitParameters) DeepCopyInto(out *ThirdPartyEnrollmentTechContactInitParameters) {
	*out = *in
	if in.AddressLineOne != nil {
		in, out := &in.AddressLineOne, &out.AddressLineOne
		*out = new(string)
		**out = **in
	}
	if in.AddressLineTwo != nil {
		in, out := &in.AddressLineTwo, &out.AddressLineTwo
		*out = new(string)
		**out = **in
	}
	if in.City != nil {
		in, out := &in.City, &out.City
		*out = new(string)
		**out = **in
	}
	if in.CountryCode != nil {
		in, out := &in.CountryCode, &out.CountryCode
		*out = new(string)
		**out = **in
	}
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(string)
		**out = **in
	}
	if in.FirstName != nil {
		in, out := &in.FirstName, &out.FirstName
		*out = new(string)
		**out = **in
	}
	if in.LastName != nil {
		in, out := &in.LastName, &out.LastName
		*out = new(string)
		**out = **in
	}
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = new(string)
		**out = **in
	}
	if in.Phone != nil {
		in, out := &in.Phone, &out.Phone
		*out = new(string)
		**out = **in
	}
	if in.PostalCode != nil {
		in, out := &in.PostalCode, &out.PostalCode
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThirdPartyEnrollmentTechContactInitParameters.
func (in *ThirdPartyEnrollmentTechContactInitParameters) DeepCopy() *ThirdPartyEnrollmentTechContactInitParameters {
	if in == nil {
		return nil
	}
	out := new(ThirdPartyEnrollmentTechContactInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThirdPartyEnrollmentTechContactObservation) DeepCopyInto(out *ThirdPartyEnrollmentTechContactObservation) {
	*out = *in
	if in.AddressLineOne != nil {
		in, out := &in.AddressLineOne, &out.AddressLineOne
		*out = new(string)
		**out = **in
	}
	if in.AddressLineTwo != nil {
		in, out := &in.AddressLineTwo, &out.AddressLineTwo
		*out = new(string)
		**out = **in
	}
	if in.City != nil {
		in, out := &in.City, &out.City
		*out = new(string)
		**out = **in
	}
	if in.CountryCode != nil {
		in, out := &in.CountryCode, &out.CountryCode
		*out = new(string)
		**out = **in
	}
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(string)
		**out = **in
	}
	if in.FirstName != nil {
		in, out := &in.FirstName, &out.FirstName
		*out = new(string)
		**out = **in
	}
	if in.LastName != nil {
		in, out := &in.LastName, &out.LastName
		*out = new(string)
		**out = **in
	}
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = new(string)
		**out = **in
	}
	if in.Phone != nil {
		in, out := &in.Phone, &out.Phone
		*out = new(string)
		**out = **in
	}
	if in.PostalCode != nil {
		in, out := &in.PostalCode, &out.PostalCode
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThirdPartyEnrollmentTechContactObservation.
func (in *ThirdPartyEnrollmentTechContactObservation) DeepCopy() *ThirdPartyEnrollmentTechContactObservation {
	if in == nil {
		return nil
	}
	out := new(ThirdPartyEnrollmentTechContactObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThirdPartyEnrollmentTechContactParameters) DeepCopyInto(out *ThirdPartyEnrollmentTechContactParameters) {
	*out = *in
	if in.AddressLineOne != nil {
		in, out := &in.AddressLineOne, &out.AddressLineOne
		*out = new(string)
		**out = **in
	}
	if in.AddressLineTwo != nil {
		in, out := &in.AddressLineTwo, &out.AddressLineTwo
		*out = new(string)
		**out = **in
	}
	if in.City != nil {
		in, out := &in.City, &out.City
		*out = new(string)
		**out = **in
	}
	if in.CountryCode != nil {
		in, out := &in.CountryCode, &out.CountryCode
		*out = new(string)
		**out = **in
	}
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(string)
		**out = **in
	}
	if in.FirstName != nil {
		in, out := &in.FirstName, &out.FirstName
		*out = new(string)
		**out = **in
	}
	if in.LastName != nil {
		in, out := &in.LastName, &out.LastName
		*out = new(string)
		**out = **in
	}
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = new(string)
		**out = **in
	}
	if in.Phone != nil {
		in, out := &in.Phone, &out.Phone
		*out = new(string)
		**out = **in
	}
	if in.PostalCode != nil {
		in, out := &in.PostalCode, &out.PostalCode
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThirdPartyEnrollmentTechContactParameters.
func (in *ThirdPartyEnrollmentTechContactParameters) DeepCopy() *ThirdPartyEnrollmentTechContactParameters {
	if in == nil {
		return nil
	}
	out := new(ThirdPartyEnrollmentTechContactParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UploadCertificate) DeepCopyInto(out *UploadCertificate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UploadCertificate.
func (in *UploadCertificate) DeepCopy() *UploadCertificate {
	if in == nil {
		return nil
	}
	out := new(UploadCertificate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UploadCertificate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UploadCertificateInitParameters) DeepCopyInto(out *UploadCertificateInitParameters) {
	*out = *in
	if in.AcknowledgeChangeManagement != nil {
		in, out := &in.AcknowledgeChangeManagement, &out.AcknowledgeChangeManagement
		*out = new(bool)
		**out = **in
	}
	if in.AcknowledgePostVerificationWarnings != nil {
		in, out := &in.AcknowledgePostVerificationWarnings, &out.AcknowledgePostVerificationWarnings
		*out = new(bool)
		**out = **in
	}
	if in.AutoApproveWarnings != nil {
		in, out := &in.AutoApproveWarnings, &out.AutoApproveWarnings
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.CertificateEcdsaPem != nil {
		in, out := &in.CertificateEcdsaPem, &out.CertificateEcdsaPem
		*out = new(string)
		**out = **in
	}
	if in.CertificateRsaPem != nil {
		in, out := &in.CertificateRsaPem, &out.CertificateRsaPem
		*out = new(string)
		**out = **in
	}
	if in.EnrollmentID != nil {
		in, out := &in.EnrollmentID, &out.EnrollmentID
		*out = new(float64)
		**out = **in
	}
	if in.TrustChainEcdsaPem != nil {
		in, out := &in.TrustChainEcdsaPem, &out.TrustChainEcdsaPem
		*out = new(string)
		**out = **in
	}
	if in.TrustChainRsaPem != nil {
		in, out := &in.TrustChainRsaPem, &out.TrustChainRsaPem
		*out = new(string)
		**out = **in
	}
	if in.WaitForDeployment != nil {
		in, out := &in.WaitForDeployment, &out.WaitForDeployment
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UploadCertificateInitParameters.
func (in *UploadCertificateInitParameters) DeepCopy() *UploadCertificateInitParameters {
	if in == nil {
		return nil
	}
	out := new(UploadCertificateInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UploadCertificateList) DeepCopyInto(out *UploadCertificateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UploadCertificate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UploadCertificateList.
func (in *UploadCertificateList) DeepCopy() *UploadCertificateList {
	if in == nil {
		return nil
	}
	out := new(UploadCertificateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UploadCertificateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UploadCertificateObservation) DeepCopyInto(out *UploadCertificateObservation) {
	*out = *in
	if in.AcknowledgeChangeManagement != nil {
		in, out := &in.AcknowledgeChangeManagement, &out.AcknowledgeChangeManagement
		*out = new(bool)
		**out = **in
	}
	if in.AcknowledgePostVerificationWarnings != nil {
		in, out := &in.AcknowledgePostVerificationWarnings, &out.AcknowledgePostVerificationWarnings
		*out = new(bool)
		**out = **in
	}
	if in.AutoApproveWarnings != nil {
		in, out := &in.AutoApproveWarnings, &out.AutoApproveWarnings
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.CertificateEcdsaPem != nil {
		in, out := &in.CertificateEcdsaPem, &out.CertificateEcdsaPem
		*out = new(string)
		**out = **in
	}
	if in.CertificateRsaPem != nil {
		in, out := &in.CertificateRsaPem, &out.CertificateRsaPem
		*out = new(string)
		**out = **in
	}
	if in.EnrollmentID != nil {
		in, out := &in.EnrollmentID, &out.EnrollmentID
		*out = new(float64)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.TrustChainEcdsaPem != nil {
		in, out := &in.TrustChainEcdsaPem, &out.TrustChainEcdsaPem
		*out = new(string)
		**out = **in
	}
	if in.TrustChainRsaPem != nil {
		in, out := &in.TrustChainRsaPem, &out.TrustChainRsaPem
		*out = new(string)
		**out = **in
	}
	if in.WaitForDeployment != nil {
		in, out := &in.WaitForDeployment, &out.WaitForDeployment
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UploadCertificateObservation.
func (in *UploadCertificateObservation) DeepCopy() *UploadCertificateObservation {
	if in == nil {
		return nil
	}
	out := new(UploadCertificateObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UploadCertificateParameters) DeepCopyInto(out *UploadCertificateParameters) {
	*out = *in
	if in.AcknowledgeChangeManagement != nil {
		in, out := &in.AcknowledgeChangeManagement, &out.AcknowledgeChangeManagement
		*out = new(bool)
		**out = **in
	}
	if in.AcknowledgePostVerificationWarnings != nil {
		in, out := &in.AcknowledgePostVerificationWarnings, &out.AcknowledgePostVerificationWarnings
		*out = new(bool)
		**out = **in
	}
	if in.AutoApproveWarnings != nil {
		in, out := &in.AutoApproveWarnings, &out.AutoApproveWarnings
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.CertificateEcdsaPem != nil {
		in, out := &in.CertificateEcdsaPem, &out.CertificateEcdsaPem
		*out = new(string)
		**out = **in
	}
	if in.CertificateRsaPem != nil {
		in, out := &in.CertificateRsaPem, &out.CertificateRsaPem
		*out = new(string)
		**out = **in
	}
	if in.EnrollmentID != nil {
		in, out := &in.EnrollmentID, &out.EnrollmentID
		*out = new(float64)
		**out = **in
	}
	if in.TrustChainEcdsaPem != nil {
		in, out := &in.TrustChainEcdsaPem, &out.TrustChainEcdsaPem
		*out = new(string)
		**out = **in
	}
	if in.TrustChainRsaPem != nil {
		in, out := &in.TrustChainRsaPem, &out.TrustChainRsaPem
		*out = new(string)
		**out = **in
	}
	if in.WaitForDeployment != nil {
		in, out := &in.WaitForDeployment, &out.WaitForDeployment
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UploadCertificateParameters.
func (in *UploadCertificateParameters) DeepCopy() *UploadCertificateParameters {
	if in == nil {
		return nil
	}
	out := new(UploadCertificateParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UploadCertificateSpec) DeepCopyInto(out *UploadCertificateSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UploadCertificateSpec.
func (in *UploadCertificateSpec) DeepCopy() *UploadCertificateSpec {
	if in == nil {
		return nil
	}
	out := new(UploadCertificateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UploadCertificateStatus) DeepCopyInto(out *UploadCertificateStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UploadCertificateStatus.
func (in *UploadCertificateStatus) DeepCopy() *UploadCertificateStatus {
	if in == nil {
		return nil
	}
	out := new(UploadCertificateStatus)
	in.DeepCopyInto(out)
	return out
}
