// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type IPAllowlistInitParameters struct {

	// Whether to enable or disable the allowlist.
	Enable *bool `json:"enable,omitempty" tf:"enable,omitempty"`
}

type IPAllowlistObservation struct {

	// Whether to enable or disable the allowlist.
	Enable *bool `json:"enable,omitempty" tf:"enable,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type IPAllowlistParameters struct {

	// Whether to enable or disable the allowlist.
	// +kubebuilder:validation:Optional
	Enable *bool `json:"enable,omitempty" tf:"enable,omitempty"`
}

// IPAllowlistSpec defines the desired state of IPAllowlist
type IPAllowlistSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     IPAllowlistParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider IPAllowlistInitParameters `json:"initProvider,omitempty"`
}

// IPAllowlistStatus defines the observed state of IPAllowlist.
type IPAllowlistStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        IPAllowlistObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// IPAllowlist is the Schema for the IPAllowlists API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,akamai}
type IPAllowlist struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.enable) || (has(self.initProvider) && has(self.initProvider.enable))",message="spec.forProvider.enable is a required parameter"
	Spec   IPAllowlistSpec   `json:"spec"`
	Status IPAllowlistStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// IPAllowlistList contains a list of IPAllowlists
type IPAllowlistList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []IPAllowlist `json:"items"`
}

// Repository type metadata.
var (
	IPAllowlist_Kind             = "IPAllowlist"
	IPAllowlist_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: IPAllowlist_Kind}.String()
	IPAllowlist_KindAPIVersion   = IPAllowlist_Kind + "." + CRDGroupVersion.String()
	IPAllowlist_GroupVersionKind = CRDGroupVersion.WithKind(IPAllowlist_Kind)
)

func init() {
	SchemeBuilder.Register(&IPAllowlist{}, &IPAllowlistList{})
}
