// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AdvancedSettingsAttackPayloadLoggingInitParameters struct {

	// Whether to enable, disable, or update attack payload logging settings
	AttackPayloadLogging *string `json:"attackPayloadLogging,omitempty" tf:"attack_payload_logging,omitempty"`

	// Unique identifier of the security configuration
	ConfigID *float64 `json:"configId,omitempty" tf:"config_id,omitempty"`

	// Unique identifier of the security policy
	SecurityPolicyID *string `json:"securityPolicyId,omitempty" tf:"security_policy_id,omitempty"`
}

type AdvancedSettingsAttackPayloadLoggingObservation struct {

	// Whether to enable, disable, or update attack payload logging settings
	AttackPayloadLogging *string `json:"attackPayloadLogging,omitempty" tf:"attack_payload_logging,omitempty"`

	// Unique identifier of the security configuration
	ConfigID *float64 `json:"configId,omitempty" tf:"config_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Unique identifier of the security policy
	SecurityPolicyID *string `json:"securityPolicyId,omitempty" tf:"security_policy_id,omitempty"`
}

type AdvancedSettingsAttackPayloadLoggingParameters struct {

	// Whether to enable, disable, or update attack payload logging settings
	// +kubebuilder:validation:Optional
	AttackPayloadLogging *string `json:"attackPayloadLogging,omitempty" tf:"attack_payload_logging,omitempty"`

	// Unique identifier of the security configuration
	// +kubebuilder:validation:Optional
	ConfigID *float64 `json:"configId,omitempty" tf:"config_id,omitempty"`

	// Unique identifier of the security policy
	// +kubebuilder:validation:Optional
	SecurityPolicyID *string `json:"securityPolicyId,omitempty" tf:"security_policy_id,omitempty"`
}

// AdvancedSettingsAttackPayloadLoggingSpec defines the desired state of AdvancedSettingsAttackPayloadLogging
type AdvancedSettingsAttackPayloadLoggingSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AdvancedSettingsAttackPayloadLoggingParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AdvancedSettingsAttackPayloadLoggingInitParameters `json:"initProvider,omitempty"`
}

// AdvancedSettingsAttackPayloadLoggingStatus defines the observed state of AdvancedSettingsAttackPayloadLogging.
type AdvancedSettingsAttackPayloadLoggingStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AdvancedSettingsAttackPayloadLoggingObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AdvancedSettingsAttackPayloadLogging is the Schema for the AdvancedSettingsAttackPayloadLoggings API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,akamai}
type AdvancedSettingsAttackPayloadLogging struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.attackPayloadLogging) || (has(self.initProvider) && has(self.initProvider.attackPayloadLogging))",message="spec.forProvider.attackPayloadLogging is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.configId) || (has(self.initProvider) && has(self.initProvider.configId))",message="spec.forProvider.configId is a required parameter"
	Spec   AdvancedSettingsAttackPayloadLoggingSpec   `json:"spec"`
	Status AdvancedSettingsAttackPayloadLoggingStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AdvancedSettingsAttackPayloadLoggingList contains a list of AdvancedSettingsAttackPayloadLoggings
type AdvancedSettingsAttackPayloadLoggingList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AdvancedSettingsAttackPayloadLogging `json:"items"`
}

// Repository type metadata.
var (
	AdvancedSettingsAttackPayloadLogging_Kind             = "AdvancedSettingsAttackPayloadLogging"
	AdvancedSettingsAttackPayloadLogging_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AdvancedSettingsAttackPayloadLogging_Kind}.String()
	AdvancedSettingsAttackPayloadLogging_KindAPIVersion   = AdvancedSettingsAttackPayloadLogging_Kind + "." + CRDGroupVersion.String()
	AdvancedSettingsAttackPayloadLogging_GroupVersionKind = CRDGroupVersion.WithKind(AdvancedSettingsAttackPayloadLogging_Kind)
)

func init() {
	SchemeBuilder.Register(&AdvancedSettingsAttackPayloadLogging{}, &AdvancedSettingsAttackPayloadLoggingList{})
}
