// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AdvancedSettingsPiiLearningInitParameters struct {

	// Unique identifier of the security configuration
	ConfigID *float64 `json:"configId,omitempty" tf:"config_id,omitempty"`

	// Whether to enable the PII learning advanced setting
	EnablePiiLearning *bool `json:"enablePiiLearning,omitempty" tf:"enable_pii_learning,omitempty"`
}

type AdvancedSettingsPiiLearningObservation struct {

	// Unique identifier of the security configuration
	ConfigID *float64 `json:"configId,omitempty" tf:"config_id,omitempty"`

	// Whether to enable the PII learning advanced setting
	EnablePiiLearning *bool `json:"enablePiiLearning,omitempty" tf:"enable_pii_learning,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type AdvancedSettingsPiiLearningParameters struct {

	// Unique identifier of the security configuration
	// +kubebuilder:validation:Optional
	ConfigID *float64 `json:"configId,omitempty" tf:"config_id,omitempty"`

	// Whether to enable the PII learning advanced setting
	// +kubebuilder:validation:Optional
	EnablePiiLearning *bool `json:"enablePiiLearning,omitempty" tf:"enable_pii_learning,omitempty"`
}

// AdvancedSettingsPiiLearningSpec defines the desired state of AdvancedSettingsPiiLearning
type AdvancedSettingsPiiLearningSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AdvancedSettingsPiiLearningParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AdvancedSettingsPiiLearningInitParameters `json:"initProvider,omitempty"`
}

// AdvancedSettingsPiiLearningStatus defines the observed state of AdvancedSettingsPiiLearning.
type AdvancedSettingsPiiLearningStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AdvancedSettingsPiiLearningObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AdvancedSettingsPiiLearning is the Schema for the AdvancedSettingsPiiLearnings API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,akamai}
type AdvancedSettingsPiiLearning struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.configId) || (has(self.initProvider) && has(self.initProvider.configId))",message="spec.forProvider.configId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.enablePiiLearning) || (has(self.initProvider) && has(self.initProvider.enablePiiLearning))",message="spec.forProvider.enablePiiLearning is a required parameter"
	Spec   AdvancedSettingsPiiLearningSpec   `json:"spec"`
	Status AdvancedSettingsPiiLearningStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AdvancedSettingsPiiLearningList contains a list of AdvancedSettingsPiiLearnings
type AdvancedSettingsPiiLearningList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AdvancedSettingsPiiLearning `json:"items"`
}

// Repository type metadata.
var (
	AdvancedSettingsPiiLearning_Kind             = "AdvancedSettingsPiiLearning"
	AdvancedSettingsPiiLearning_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AdvancedSettingsPiiLearning_Kind}.String()
	AdvancedSettingsPiiLearning_KindAPIVersion   = AdvancedSettingsPiiLearning_Kind + "." + CRDGroupVersion.String()
	AdvancedSettingsPiiLearning_GroupVersionKind = CRDGroupVersion.WithKind(AdvancedSettingsPiiLearning_Kind)
)

func init() {
	SchemeBuilder.Register(&AdvancedSettingsPiiLearning{}, &AdvancedSettingsPiiLearningList{})
}
