// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type BypassNetworkListsInitParameters struct {

	// List of network list IDs that compose the bypass list
	// +listType=set
	BypassNetworkList []*string `json:"bypassNetworkList,omitempty" tf:"bypass_network_list,omitempty"`

	// Unique identifier of the security configuration
	ConfigID *float64 `json:"configId,omitempty" tf:"config_id,omitempty"`

	// The unique identifier of the security policy governing the bypass network lists
	SecurityPolicyID *string `json:"securityPolicyId,omitempty" tf:"security_policy_id,omitempty"`
}

type BypassNetworkListsObservation struct {

	// List of network list IDs that compose the bypass list
	// +listType=set
	BypassNetworkList []*string `json:"bypassNetworkList,omitempty" tf:"bypass_network_list,omitempty"`

	// Unique identifier of the security configuration
	ConfigID *float64 `json:"configId,omitempty" tf:"config_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The unique identifier of the security policy governing the bypass network lists
	SecurityPolicyID *string `json:"securityPolicyId,omitempty" tf:"security_policy_id,omitempty"`
}

type BypassNetworkListsParameters struct {

	// List of network list IDs that compose the bypass list
	// +kubebuilder:validation:Optional
	// +listType=set
	BypassNetworkList []*string `json:"bypassNetworkList,omitempty" tf:"bypass_network_list,omitempty"`

	// Unique identifier of the security configuration
	// +kubebuilder:validation:Optional
	ConfigID *float64 `json:"configId,omitempty" tf:"config_id,omitempty"`

	// The unique identifier of the security policy governing the bypass network lists
	// +kubebuilder:validation:Optional
	SecurityPolicyID *string `json:"securityPolicyId,omitempty" tf:"security_policy_id,omitempty"`
}

// BypassNetworkListsSpec defines the desired state of BypassNetworkLists
type BypassNetworkListsSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     BypassNetworkListsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider BypassNetworkListsInitParameters `json:"initProvider,omitempty"`
}

// BypassNetworkListsStatus defines the observed state of BypassNetworkLists.
type BypassNetworkListsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        BypassNetworkListsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// BypassNetworkLists is the Schema for the BypassNetworkListss API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,akamai}
type BypassNetworkLists struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.bypassNetworkList) || (has(self.initProvider) && has(self.initProvider.bypassNetworkList))",message="spec.forProvider.bypassNetworkList is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.configId) || (has(self.initProvider) && has(self.initProvider.configId))",message="spec.forProvider.configId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.securityPolicyId) || (has(self.initProvider) && has(self.initProvider.securityPolicyId))",message="spec.forProvider.securityPolicyId is a required parameter"
	Spec   BypassNetworkListsSpec   `json:"spec"`
	Status BypassNetworkListsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BypassNetworkListsList contains a list of BypassNetworkListss
type BypassNetworkListsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BypassNetworkLists `json:"items"`
}

// Repository type metadata.
var (
	BypassNetworkLists_Kind             = "BypassNetworkLists"
	BypassNetworkLists_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: BypassNetworkLists_Kind}.String()
	BypassNetworkLists_KindAPIVersion   = BypassNetworkLists_Kind + "." + CRDGroupVersion.String()
	BypassNetworkLists_GroupVersionKind = CRDGroupVersion.WithKind(BypassNetworkLists_Kind)
)

func init() {
	SchemeBuilder.Register(&BypassNetworkLists{}, &BypassNetworkListsList{})
}
