apiVersion: cloudlets.akamai.footprintit.net/v1alpha1
kind: Policy
metadata:
  annotations:
    meta.upbound.io/example-id: akamai/cloudlets/v1alpha1/policy
  labels:
    testing.upbound.io/example-name: test-cloudlet-policy
  name: test-cloudlet-policy
spec:
  forProvider:
    name: Test_Cloudlet_Policy
    cloudletCode: IG
    description: Test Cloudlet Policy
    groupId: "123456"
    matchRules: |
      [
        {
          "name": "rule1",
          "type": "igMatchRule",
          "allowDeny": "allow",
          "matches": [
            {
              "matchValue": "8.8.8.8",
              "matchOperator": "equals",
              "negate": false,
              "caseSensitive": false,
              "checkIPs": "CONNECTING_IP XFF_HEADERS",
              "matchType": "clientip"
            }
          ]
        }
      ]
