// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type BotManagementSettingsInitParameters struct {
	BotManagementSettings *string `json:"botManagementSettings,omitempty" tf:"bot_management_settings,omitempty"`

	ConfigID *float64 `json:"configId,omitempty" tf:"config_id,omitempty"`

	SecurityPolicyID *string `json:"securityPolicyId,omitempty" tf:"security_policy_id,omitempty"`
}

type BotManagementSettingsObservation struct {
	BotManagementSettings *string `json:"botManagementSettings,omitempty" tf:"bot_management_settings,omitempty"`

	ConfigID *float64 `json:"configId,omitempty" tf:"config_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	SecurityPolicyID *string `json:"securityPolicyId,omitempty" tf:"security_policy_id,omitempty"`
}

type BotManagementSettingsParameters struct {

	// +kubebuilder:validation:Optional
	BotManagementSettings *string `json:"botManagementSettings,omitempty" tf:"bot_management_settings,omitempty"`

	// +kubebuilder:validation:Optional
	ConfigID *float64 `json:"configId,omitempty" tf:"config_id,omitempty"`

	// +kubebuilder:validation:Optional
	SecurityPolicyID *string `json:"securityPolicyId,omitempty" tf:"security_policy_id,omitempty"`
}

// BotManagementSettingsSpec defines the desired state of BotManagementSettings
type BotManagementSettingsSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     BotManagementSettingsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider BotManagementSettingsInitParameters `json:"initProvider,omitempty"`
}

// BotManagementSettingsStatus defines the observed state of BotManagementSettings.
type BotManagementSettingsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        BotManagementSettingsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// BotManagementSettings is the Schema for the BotManagementSettingss API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,akamai}
type BotManagementSettings struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.botManagementSettings) || (has(self.initProvider) && has(self.initProvider.botManagementSettings))",message="spec.forProvider.botManagementSettings is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.configId) || (has(self.initProvider) && has(self.initProvider.configId))",message="spec.forProvider.configId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.securityPolicyId) || (has(self.initProvider) && has(self.initProvider.securityPolicyId))",message="spec.forProvider.securityPolicyId is a required parameter"
	Spec   BotManagementSettingsSpec   `json:"spec"`
	Status BotManagementSettingsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BotManagementSettingsList contains a list of BotManagementSettingss
type BotManagementSettingsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BotManagementSettings `json:"items"`
}

// Repository type metadata.
var (
	BotManagementSettings_Kind             = "BotManagementSettings"
	BotManagementSettings_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: BotManagementSettings_Kind}.String()
	BotManagementSettings_KindAPIVersion   = BotManagementSettings_Kind + "." + CRDGroupVersion.String()
	BotManagementSettings_GroupVersionKind = CRDGroupVersion.WithKind(BotManagementSettings_Kind)
)

func init() {
	SchemeBuilder.Register(&BotManagementSettings{}, &BotManagementSettingsList{})
}
