// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ContentProtectionRuleInitParameters struct {

	// Unique identifier of the security configuration
	ConfigID *float64 `json:"configId,omitempty" tf:"config_id,omitempty"`

	// The content protection rule
	ContentProtectionRule *string `json:"contentProtectionRule,omitempty" tf:"content_protection_rule,omitempty"`

	// Unique identifier of the security policy
	SecurityPolicyID *string `json:"securityPolicyId,omitempty" tf:"security_policy_id,omitempty"`
}

type ContentProtectionRuleObservation struct {

	// Unique identifier of the security configuration
	ConfigID *float64 `json:"configId,omitempty" tf:"config_id,omitempty"`

	// The content protection rule
	ContentProtectionRule *string `json:"contentProtectionRule,omitempty" tf:"content_protection_rule,omitempty"`

	// Unique identifier of a content protection rule
	ContentProtectionRuleID *string `json:"contentProtectionRuleId,omitempty" tf:"content_protection_rule_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Unique identifier of the security policy
	SecurityPolicyID *string `json:"securityPolicyId,omitempty" tf:"security_policy_id,omitempty"`
}

type ContentProtectionRuleParameters struct {

	// Unique identifier of the security configuration
	// +kubebuilder:validation:Optional
	ConfigID *float64 `json:"configId,omitempty" tf:"config_id,omitempty"`

	// The content protection rule
	// +kubebuilder:validation:Optional
	ContentProtectionRule *string `json:"contentProtectionRule,omitempty" tf:"content_protection_rule,omitempty"`

	// Unique identifier of the security policy
	// +kubebuilder:validation:Optional
	SecurityPolicyID *string `json:"securityPolicyId,omitempty" tf:"security_policy_id,omitempty"`
}

// ContentProtectionRuleSpec defines the desired state of ContentProtectionRule
type ContentProtectionRuleSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ContentProtectionRuleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ContentProtectionRuleInitParameters `json:"initProvider,omitempty"`
}

// ContentProtectionRuleStatus defines the observed state of ContentProtectionRule.
type ContentProtectionRuleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ContentProtectionRuleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ContentProtectionRule is the Schema for the ContentProtectionRules API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,akamai}
type ContentProtectionRule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.configId) || (has(self.initProvider) && has(self.initProvider.configId))",message="spec.forProvider.configId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.contentProtectionRule) || (has(self.initProvider) && has(self.initProvider.contentProtectionRule))",message="spec.forProvider.contentProtectionRule is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.securityPolicyId) || (has(self.initProvider) && has(self.initProvider.securityPolicyId))",message="spec.forProvider.securityPolicyId is a required parameter"
	Spec   ContentProtectionRuleSpec   `json:"spec"`
	Status ContentProtectionRuleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ContentProtectionRuleList contains a list of ContentProtectionRules
type ContentProtectionRuleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ContentProtectionRule `json:"items"`
}

// Repository type metadata.
var (
	ContentProtectionRule_Kind             = "ContentProtectionRule"
	ContentProtectionRule_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ContentProtectionRule_Kind}.String()
	ContentProtectionRule_KindAPIVersion   = ContentProtectionRule_Kind + "." + CRDGroupVersion.String()
	ContentProtectionRule_GroupVersionKind = CRDGroupVersion.WithKind(ContentProtectionRule_Kind)
)

func init() {
	SchemeBuilder.Register(&ContentProtectionRule{}, &ContentProtectionRuleList{})
}
