// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type CustomClientInitParameters struct {
	ConfigID *float64 `json:"configId,omitempty" tf:"config_id,omitempty"`

	CustomClient *string `json:"customClient,omitempty" tf:"custom_client,omitempty"`
}

type CustomClientObservation struct {
	ConfigID *float64 `json:"configId,omitempty" tf:"config_id,omitempty"`

	CustomClient *string `json:"customClient,omitempty" tf:"custom_client,omitempty"`

	CustomClientID *string `json:"customClientId,omitempty" tf:"custom_client_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type CustomClientParameters struct {

	// +kubebuilder:validation:Optional
	ConfigID *float64 `json:"configId,omitempty" tf:"config_id,omitempty"`

	// +kubebuilder:validation:Optional
	CustomClient *string `json:"customClient,omitempty" tf:"custom_client,omitempty"`
}

// CustomClientSpec defines the desired state of CustomClient
type CustomClientSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     CustomClientParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CustomClientInitParameters `json:"initProvider,omitempty"`
}

// CustomClientStatus defines the observed state of CustomClient.
type CustomClientStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CustomClientObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// CustomClient is the Schema for the CustomClients API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,akamai}
type CustomClient struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.configId) || (has(self.initProvider) && has(self.initProvider.configId))",message="spec.forProvider.configId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.customClient) || (has(self.initProvider) && has(self.initProvider.customClient))",message="spec.forProvider.customClient is a required parameter"
	Spec   CustomClientSpec   `json:"spec"`
	Status CustomClientStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CustomClientList contains a list of CustomClients
type CustomClientList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CustomClient `json:"items"`
}

// Repository type metadata.
var (
	CustomClient_Kind             = "CustomClient"
	CustomClient_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CustomClient_Kind}.String()
	CustomClient_KindAPIVersion   = CustomClient_Kind + "." + CRDGroupVersion.String()
	CustomClient_GroupVersionKind = CRDGroupVersion.WithKind(CustomClient_Kind)
)

func init() {
	SchemeBuilder.Register(&CustomClient{}, &CustomClientList{})
}
