// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ConditionalActionInitParameters struct {
	ConditionalAction *string `json:"conditionalAction,omitempty" tf:"conditional_action,omitempty"`

	ConfigID *float64 `json:"configId,omitempty" tf:"config_id,omitempty"`
}

type ConditionalActionObservation struct {
	ActionID *string `json:"actionId,omitempty" tf:"action_id,omitempty"`

	ConditionalAction *string `json:"conditionalAction,omitempty" tf:"conditional_action,omitempty"`

	ConfigID *float64 `json:"configId,omitempty" tf:"config_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type ConditionalActionParameters struct {

	// +kubebuilder:validation:Optional
	ConditionalAction *string `json:"conditionalAction,omitempty" tf:"conditional_action,omitempty"`

	// +kubebuilder:validation:Optional
	ConfigID *float64 `json:"configId,omitempty" tf:"config_id,omitempty"`
}

// ConditionalActionSpec defines the desired state of ConditionalAction
type ConditionalActionSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ConditionalActionParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ConditionalActionInitParameters `json:"initProvider,omitempty"`
}

// ConditionalActionStatus defines the observed state of ConditionalAction.
type ConditionalActionStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ConditionalActionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ConditionalAction is the Schema for the ConditionalActions API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,akamai}
type ConditionalAction struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.conditionalAction) || (has(self.initProvider) && has(self.initProvider.conditionalAction))",message="spec.forProvider.conditionalAction is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.configId) || (has(self.initProvider) && has(self.initProvider.configId))",message="spec.forProvider.configId is a required parameter"
	Spec   ConditionalActionSpec   `json:"spec"`
	Status ConditionalActionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ConditionalActionList contains a list of ConditionalActions
type ConditionalActionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ConditionalAction `json:"items"`
}

// Repository type metadata.
var (
	ConditionalAction_Kind             = "ConditionalAction"
	ConditionalAction_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ConditionalAction_Kind}.String()
	ConditionalAction_KindAPIVersion   = ConditionalAction_Kind + "." + CRDGroupVersion.String()
	ConditionalAction_GroupVersionKind = CRDGroupVersion.WithKind(ConditionalAction_Kind)
)

func init() {
	SchemeBuilder.Register(&ConditionalAction{}, &ConditionalActionList{})
}
