// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ContentProtectionJavascriptInjectionRuleInitParameters struct {

	// Unique identifier of the security configuration
	ConfigID *float64 `json:"configId,omitempty" tf:"config_id,omitempty"`

	// The content protection JavaScript injection rule
	ContentProtectionJavascriptInjectionRule *string `json:"contentProtectionJavascriptInjectionRule,omitempty" tf:"content_protection_javascript_injection_rule,omitempty"`

	// Unique identifier of the security policy
	SecurityPolicyID *string `json:"securityPolicyId,omitempty" tf:"security_policy_id,omitempty"`
}

type ContentProtectionJavascriptInjectionRuleObservation struct {

	// Unique identifier of the security configuration
	ConfigID *float64 `json:"configId,omitempty" tf:"config_id,omitempty"`

	// The content protection JavaScript injection rule
	ContentProtectionJavascriptInjectionRule *string `json:"contentProtectionJavascriptInjectionRule,omitempty" tf:"content_protection_javascript_injection_rule,omitempty"`

	// Unique identifier of a content protection JavaScript injection rule
	ContentProtectionJavascriptInjectionRuleID *string `json:"contentProtectionJavascriptInjectionRuleId,omitempty" tf:"content_protection_javascript_injection_rule_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Unique identifier of the security policy
	SecurityPolicyID *string `json:"securityPolicyId,omitempty" tf:"security_policy_id,omitempty"`
}

type ContentProtectionJavascriptInjectionRuleParameters struct {

	// Unique identifier of the security configuration
	// +kubebuilder:validation:Optional
	ConfigID *float64 `json:"configId,omitempty" tf:"config_id,omitempty"`

	// The content protection JavaScript injection rule
	// +kubebuilder:validation:Optional
	ContentProtectionJavascriptInjectionRule *string `json:"contentProtectionJavascriptInjectionRule,omitempty" tf:"content_protection_javascript_injection_rule,omitempty"`

	// Unique identifier of the security policy
	// +kubebuilder:validation:Optional
	SecurityPolicyID *string `json:"securityPolicyId,omitempty" tf:"security_policy_id,omitempty"`
}

// ContentProtectionJavascriptInjectionRuleSpec defines the desired state of ContentProtectionJavascriptInjectionRule
type ContentProtectionJavascriptInjectionRuleSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ContentProtectionJavascriptInjectionRuleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ContentProtectionJavascriptInjectionRuleInitParameters `json:"initProvider,omitempty"`
}

// ContentProtectionJavascriptInjectionRuleStatus defines the observed state of ContentProtectionJavascriptInjectionRule.
type ContentProtectionJavascriptInjectionRuleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ContentProtectionJavascriptInjectionRuleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ContentProtectionJavascriptInjectionRule is the Schema for the ContentProtectionJavascriptInjectionRules API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,akamai}
type ContentProtectionJavascriptInjectionRule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.configId) || (has(self.initProvider) && has(self.initProvider.configId))",message="spec.forProvider.configId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.contentProtectionJavascriptInjectionRule) || (has(self.initProvider) && has(self.initProvider.contentProtectionJavascriptInjectionRule))",message="spec.forProvider.contentProtectionJavascriptInjectionRule is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.securityPolicyId) || (has(self.initProvider) && has(self.initProvider.securityPolicyId))",message="spec.forProvider.securityPolicyId is a required parameter"
	Spec   ContentProtectionJavascriptInjectionRuleSpec   `json:"spec"`
	Status ContentProtectionJavascriptInjectionRuleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ContentProtectionJavascriptInjectionRuleList contains a list of ContentProtectionJavascriptInjectionRules
type ContentProtectionJavascriptInjectionRuleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ContentProtectionJavascriptInjectionRule `json:"items"`
}

// Repository type metadata.
var (
	ContentProtectionJavascriptInjectionRule_Kind             = "ContentProtectionJavascriptInjectionRule"
	ContentProtectionJavascriptInjectionRule_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ContentProtectionJavascriptInjectionRule_Kind}.String()
	ContentProtectionJavascriptInjectionRule_KindAPIVersion   = ContentProtectionJavascriptInjectionRule_Kind + "." + CRDGroupVersion.String()
	ContentProtectionJavascriptInjectionRule_GroupVersionKind = CRDGroupVersion.WithKind(ContentProtectionJavascriptInjectionRule_Kind)
)

func init() {
	SchemeBuilder.Register(&ContentProtectionJavascriptInjectionRule{}, &ContentProtectionJavascriptInjectionRuleList{})
}
